<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="zh_CN" sourcelanguage="en">
<context>
    <name>About</name>
    <message>
        <location filename="../About.cpp" line="119"/>
        <source>About</source>
        <translation>关于</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <location filename="../copyablelineedit.ui" line="84"/>
        <source>Copy to clipboard</source>
        <translation>复制到剪贴板</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <location filename="../DockConf.cpp" line="361"/>
        <location filename="../DockConf.cpp" line="362"/>
        <source>Configuration</source>
        <translation>设置</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="363"/>
        <source>Output Format</source>
        <translation>输出格式</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="364"/>
        <source>Columns</source>
        <translation>列</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="365"/>
        <source>Rows</source>
        <translation>行</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="366"/>
        <source>Width</source>
        <translation>宽度</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="367"/>
        <source>Gap</source>
        <translation>间距</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="368"/>
        <source>Quality</source>
        <translation>图像质量</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="369"/>
        <source>Blank skip</source>
        <translation>空白度</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="370"/>
        <source>Edge detection</source>
        <translation>角度</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <location filename="../DockInputOutput.cpp" line="55"/>
        <location filename="../DockInputOutput.cpp" line="432"/>
        <source>Path Output</source>
        <translation>目标文件夹</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="70"/>
        <location filename="../DockInputOutput.cpp" line="434"/>
        <source>Same folder output as source</source>
        <translation>与源文件保存在同一文件夹</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="374"/>
        <source>Media list is already empty</source>
        <translation>媒体列表已空</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="427"/>
        <source>Input and Output</source>
        <translation>输入与输出</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="428"/>
        <source>Load</source>
        <translation>打开</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="429"/>
        <source>Reset</source>
        <translation>删除全部</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="430"/>
        <source>Start</source>
        <translation>开始</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="431"/>
        <source>Delete Selection</source>
        <translation>删除所选</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="433"/>
        <source>Preview selection file</source>
        <translation>预览选定文件</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <location filename="../DockStyles.cpp" line="527"/>
        <location filename="../DockStyles.cpp" line="528"/>
        <source>Styles</source>
        <translation>风格</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="529"/>
        <source>Generated by Thumbnail me</source>
        <translation>Thumbnail me 制作</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="530"/>
        <source>Info Text</source>
        <translation>技术细节</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="531"/>
        <source>Timestamp</source>
        <translation>时戳</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="535"/>
        <location filename="../DockStyles.cpp" line="536"/>
        <source>Building Font Cache...</source>
        <translation>字体索引中...</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Left</source>
        <translation>左下方</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Right</source>
        <translation>右下方</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Right</source>
        <translation>右上方</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Left</source>
        <translation>左上方</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="532"/>
        <source>Additional Title</source>
        <translation>额外标题</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="533"/>
        <source>Background Color</source>
        <translation>背景颜色</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="534"/>
        <source>Shadow Color</source>
        <translation>阴影颜色</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <location filename="../DockTimeLine.cpp" line="185"/>
        <location filename="../DockTimeLine.cpp" line="192"/>
        <location filename="../DockTimeLine.cpp" line="206"/>
        <source>TimeLine</source>
        <translation>时间轴</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="142"/>
        <location filename="../DockTimeLine.cpp" line="186"/>
        <location filename="../DockTimeLine.cpp" line="193"/>
        <location filename="../DockTimeLine.cpp" line="200"/>
        <location filename="../DockTimeLine.cpp" line="207"/>
        <source>From</source>
        <translation>从</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="153"/>
        <location filename="../DockTimeLine.cpp" line="187"/>
        <location filename="../DockTimeLine.cpp" line="194"/>
        <location filename="../DockTimeLine.cpp" line="201"/>
        <location filename="../DockTimeLine.cpp" line="208"/>
        <source>To</source>
        <translation>至</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="188"/>
        <location filename="../DockTimeLine.cpp" line="195"/>
        <location filename="../DockTimeLine.cpp" line="202"/>
        <location filename="../DockTimeLine.cpp" line="209"/>
        <source>Total duration</source>
        <translation>总时间</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="131"/>
        <location filename="../DockTimeLine.cpp" line="199"/>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>时间轴 (无) | 媒体文件格式不支持</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <location filename="../FontMapComboBox.cpp" line="132"/>
        <source>No fonts defined</source>
        <translation>无已定义字体</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="197"/>
        <source>Add</source>
        <translation>添加</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="198"/>
        <source>Remove</source>
        <translation>删除</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="87"/>
        <source>No fonts found in this folder</source>
        <translation>此文件夹不包含字体文件 (*.ttf)</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="81"/>
        <source>Select a font folder</source>
        <translation>选择一包含字体的文件夹</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="96"/>
        <source>You must select a path to remove it from the list</source>
        <translation>您必须至少选择一个路径以便从列表中删除</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="239"/>
        <source>Never ask me to save my configuration on exit</source>
        <translation>退出时不再询问是否保存当前设置</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="240"/>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>软件启动时不自动导入上次设置文件</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="241"/>
        <source>Background color of preview window</source>
        <translation>预览窗口的背景色</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="242"/>
        <source>Output suffix:</source>
        <translation>输出后缀 :</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="49"/>
        <location filename="../GeneralSettingsTab.cpp" line="243"/>
        <source>Activate openGL to preview thumbnails</source>
        <translation>启用openGL预览缩略图</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="52"/>
        <location filename="../GeneralSettingsTab.cpp" line="244"/>
        <source>Animate pixmap while rendering</source>
        <translation>开启缩略图的动画效果</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="238"/>
        <source>General Settings</source>
        <translation>常规设置</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <location filename="../HelpWidget.cpp" line="110"/>
        <source>Help</source>
        <translation>帮助</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="426"/>
        <source>Password</source>
        <translation>密码</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="427"/>
        <source>Remember Password</source>
        <translation>记住密码</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="55"/>
        <location filename="../ImageShackLoginWidget.cpp" line="429"/>
        <source>Login</source>
        <translation>登录</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="87"/>
        <location filename="../ImageShackLoginWidget.cpp" line="430"/>
        <source>Login in progress...</source>
        <translation>正在登录...</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="89"/>
        <location filename="../ImageShackLoginWidget.cpp" line="432"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="225"/>
        <source>Authentication failed. Check your username and password.</source>
        <translation>登录失败。请检查您的用户名和密码。</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="239"/>
        <source>Connection refused</source>
        <translation>登入失败</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="240"/>
        <source>Remote host closed</source>
        <translation>远程主机关闭</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="241"/>
        <source>Host not found</source>
        <translation>未发现主机</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="242"/>
        <source>Timeout</source>
        <translation>超时</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="243"/>
        <source>Operation canceled</source>
        <translation>操作取消</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="244"/>
        <source>SSL handshake failed</source>
        <translation>SSL初始化失败</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="245"/>
        <source>Proxy connection refused</source>
        <translation>连接到代理被拒绝</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="246"/>
        <source>Proxy connection closed</source>
        <translation>连接到代立理关闭</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="247"/>
        <source>Proxy not found</source>
        <translation>未找到代理</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="248"/>
        <source>Proxy timeout</source>
        <translation>连接到代理超时</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="249"/>
        <source>Proxy authentication required</source>
        <translation>连接到代理需要验证</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="250"/>
        <source>Content access denied</source>
        <translation>内容禁止访问</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="251"/>
        <source>Content operation not permitted</source>
        <translation>操作禁止</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="252"/>
        <source>Content not found</source>
        <translation>未找到内容</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="253"/>
        <source>Authentication required</source>
        <translation>需要验证</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="254"/>
        <source>Protocol unknown</source>
        <translation>未知协议</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="255"/>
        <source>Protocol invalid operation</source>
        <translation>无效协议</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="256"/>
        <source>Unknown network</source>
        <translation>未知网络</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="257"/>
        <source>Unknown proxy</source>
        <translation>未知代理</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="258"/>
        <source>Unknown content</source>
        <translation>未知内容</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="259"/>
        <source>Protocol failure</source>
        <translation>协议错误</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="260"/>
        <source>Content resend</source>
        <translation>内容重发</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="261"/>
        <source>Temporary network failure</source>
        <translation>临时网络故障</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="262"/>
        <location filename="../ImageShackLoginWidget.cpp" line="266"/>
        <source>Unknown error</source>
        <translation>未知错误</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="263"/>
        <source>Failed to open the file</source>
        <translation>阅读文件失败</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="264"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>达到文件最大限制 (5 Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="270"/>
        <source>Upload Error:</source>
        <translation>上传错误 :</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="297"/>
        <source>Login as</source>
        <translation>登录为</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="425"/>
        <source>Username/E-mail</source>
        <translation>用户名/邮箱地址</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="428"/>
        <source>Autologin</source>
        <translation>自动登录</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="102"/>
        <location filename="../ImageShackLoginWidget.cpp" line="431"/>
        <source>Logout</source>
        <translation>退出</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="20"/>
        <source>Uploaded files</source>
        <translation>已上传文件</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="109"/>
        <source>File 1 of 1</source>
        <translation>文件 1 / 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="334"/>
        <source>Close</source>
        <translation>退出</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="178"/>
        <source>Direct link</source>
        <translation>直接链接</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="179"/>
        <source>Short link</source>
        <translation>短链接</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="180"/>
        <source>Hotlink for web</source>
        <translation>网页Hotlink</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="181"/>
        <source>Thumbnail for web</source>
        <translation>网页缩略图</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="182"/>
        <source>Thumbnail for forums 1</source>
        <translation>论坛缩略图 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="183"/>
        <source>Thumbnail for forums 2</source>
        <translation>论坛缩略图 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="184"/>
        <source>Hotlink for forums 1</source>
        <translation>论坛Hotlink 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="185"/>
        <source>Hotlink for forums 2</source>
        <translation>论坛Hotlink 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="100"/>
        <source>File %1 of %2</source>
        <translation>文件 %1 / %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>Upload mode:</source>
        <translation>上传模式 :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="136"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;上传模式: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;匿名&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="215"/>
        <location filename="../ImageShackUploadWidget.cpp" line="247"/>
        <source>File loaded: %1</source>
        <translation>已导入文件: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="299"/>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;调整图像大小:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="310"/>
        <source>Do not resize</source>
        <translation>不调整图像大小</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="315"/>
        <source>100x100 (avatar)</source>
        <translation>100x100 (头像)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="320"/>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (缩略图)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="325"/>
        <source>320x320 (for websites and email)</source>
        <translation> 320x320 (网页或邮件)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="330"/>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (留言板)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="335"/>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (12寸屏幕)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="340"/>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (15寸屏幕)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="345"/>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (19寸屏幕)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="350"/>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (21寸屏幕)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="423"/>
        <source>Comma separated list</source>
        <translation>用逗号隔开</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="640"/>
        <source>Upload in progress...</source>
        <translation>上传中...</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="361"/>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;隐私权:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="371"/>
        <source>Private</source>
        <translation>私人</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="381"/>
        <source>Public</source>
        <translation>公开</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="394"/>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>标签</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="459"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;您登入后才能修改标签和隐私权。&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="552"/>
        <source>Upload now</source>
        <translation>上传</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="647"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="685"/>
        <source>File upload progress:</source>
        <translation>文件上传进度 :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="709"/>
        <source>Total upload progress:</source>
        <translation>文件上传总进度 :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="146"/>
        <source>File(s) loaded: %1</source>
        <translation>已上传文件: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <source>login</source>
        <translation>用户名</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>anonymous</source>
        <translation>匿名</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="30"/>
        <source>Log in to use this features</source>
        <translation>您登入后才能使用此功能</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="212"/>
        <source>Log in to use these features</source>
        <translation>您登入后才能使用这些功能</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="229"/>
        <location filename="../ImageShackUploadWidget.cpp" line="272"/>
        <source>Processing file %1 of %2</source>
        <translation>文件处理中 %1 / %2</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="359"/>
        <source>Connection refused</source>
        <translation>登入失败</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="360"/>
        <source>Remote host closed</source>
        <translation>远程主机关闭</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="361"/>
        <source>Host not found</source>
        <translation>未发现主机</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="362"/>
        <source>Timeout</source>
        <translation>超时</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="363"/>
        <source>Operation canceled</source>
        <translation>操作取消</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="364"/>
        <source>SSL handshake failed</source>
        <translation>SSL初始化失败</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="365"/>
        <source>Proxy connection refused</source>
        <translation>连接到代理被拒绝</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="366"/>
        <source>Proxy connection closed</source>
        <translation>连接到代立理关闭</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="367"/>
        <source>Proxy not found</source>
        <translation>未找到代理</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="368"/>
        <source>Proxy timeout</source>
        <translation>连接到代理超时</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="369"/>
        <source>Proxy authentication required</source>
        <translation>连接到代理需要验证</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="370"/>
        <source>Content access denied</source>
        <translation>内容禁止访问</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="371"/>
        <source>Content operation not permitted</source>
        <translation>操作禁止</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="372"/>
        <source>Content not found</source>
        <translation>未找到内容</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="373"/>
        <source>Authentication required</source>
        <translation>需要验证</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="374"/>
        <source>Protocol unknown</source>
        <translation>未知协议</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="375"/>
        <source>Protocol invalid operation</source>
        <translation>无效协议</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="376"/>
        <source>Unknown network</source>
        <translation>未知网络</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="377"/>
        <source>Unknown proxy</source>
        <translation>未知代理</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="378"/>
        <source>Unknown content</source>
        <translation>未知内容</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="379"/>
        <source>Protocol failure</source>
        <translation>协议错误</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="380"/>
        <source>Content resend</source>
        <translation>内容重发</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="381"/>
        <source>Temporary network failure</source>
        <translation>临时网络故障</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="382"/>
        <location filename="../ImageShackUploadWidget.cpp" line="386"/>
        <source>Unknown error</source>
        <translation>未知错误</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="383"/>
        <source>Failed to open the file</source>
        <translation>阅读文件失败</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="384"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>达到文件最大限制 (5 Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="391"/>
        <source>Upload Error:</source>
        <translation>上传错误 :</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <source>Open Configuration File</source>
        <translation>打开设置文件</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Configuration file(*.ini)</source>
        <translation>设置文件(*.ini)</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="82"/>
        <location filename="../IniManager.cpp" line="219"/>
        <location filename="../IniManager.cpp" line="230"/>
        <location filename="../IniManager.cpp" line="241"/>
        <location filename="../IniManager.cpp" line="252"/>
        <location filename="../IniManager.cpp" line="335"/>
        <source>Configuration file loaded</source>
        <translation>设置文件已导入</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="85"/>
        <source>Incorrect settings file</source>
        <translation>设置文件错误</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source>Configuration file</source>
        <translation>设置文件</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source> saved successfully</source>
        <translation>保存成功</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Save Configuration File</source>
        <translation>保存设置文件</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="274"/>
        <source>Not recent files</source>
        <translation>无近期设置文件</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="223"/>
        <source>English</source>
        <translation>英语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="224"/>
        <source>French</source>
        <translation>法语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="225"/>
        <source>Spanish</source>
        <translation>西班牙语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="226"/>
        <source>German</source>
        <translation>德语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="227"/>
        <source>Dutch</source>
        <translation>荷兰语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="228"/>
        <source>Italian</source>
        <translation>意大利语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="229"/>
        <source>Czech</source>
        <translation>捷克语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="230"/>
        <source>Hungarian</source>
        <translation>匈牙利语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="231"/>
        <source>Croatian</source>
        <translation>克罗地亚语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="232"/>
        <source>Portuguese</source>
        <translation>西班牙语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="233"/>
        <source>Chinese</source>
        <translation>简体中文</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="234"/>
        <source>Russian</source>
        <translation>俄语</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="109"/>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="222"/>
        <source>Select a language</source>
        <translation>选择语言</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="107"/>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="108"/>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../MainWindow.cpp" line="286"/>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>无法导入上次设置文件。所有设置将被重置。</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="384"/>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>退出前是否保存当前 Thumbnail me 设置?</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="388"/>
        <source>saved successfully</source>
        <translation>保存成功</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="480"/>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>不包含TrueType字体文件。请从设置菜单中选择包含其他字体的文件夹。</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="553"/>
        <source>Toolbar</source>
        <translation>工具栏</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="555"/>
        <source>File</source>
        <translation>文件</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="556"/>
        <source>Edition</source>
        <translation>编辑</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="557"/>
        <source>View</source>
        <translation>查看</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="558"/>
        <source>Predefined Configuration</source>
        <translation>默认设置</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="559"/>
        <location filename="../MainWindow.cpp" line="576"/>
        <source>About</source>
        <translation>关于</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="562"/>
        <source>Configuration</source>
        <translation>设置</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="563"/>
        <source>Open</source>
        <translation>打开</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="564"/>
        <source>Import a configuration file</source>
        <translation>导入设置文件</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="565"/>
        <source>Import a recent configuration file</source>
        <translation>导入近期设置文件</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="566"/>
        <source>Save my current configuration</source>
        <translation>保存当前设置</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="567"/>
        <source>Save my current configuration as</source>
        <translation>保存当前设置于</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="568"/>
        <source>Print</source>
        <translation>打印</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="569"/>
        <source>Exit</source>
        <translation>退出</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="570"/>
        <source>Settings</source>
        <translation>设置</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="571"/>
        <source>Zoom in</source>
        <translation>放大</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="572"/>
        <source>Zoom out</source>
        <translation>缩小</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="573"/>
        <source>Clear all</source>
        <translation>清除全部</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="574"/>
        <source>Fullscreen</source>
        <translation>全屏</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="575"/>
        <source>Help</source>
        <translation>帮助</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="577"/>
        <source>About QT</source>
        <translation>关于QT</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="578"/>
        <source>Donate</source>
        <translation>捐赠</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="579"/>
        <source>Website</source>
        <translation>网址</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="307"/>
        <source>Network Connection</source>
        <translation>网络连接</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="308"/>
        <source>Direct connection</source>
        <translation>直接连接</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="309"/>
        <source>Use proxy server</source>
        <translation>使用代理</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="310"/>
        <source>Hostname</source>
        <translation>主机名</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="311"/>
        <source>Port</source>
        <translation>端口</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="312"/>
        <source>Type</source>
        <translation>类型</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="313"/>
        <source>Authentication</source>
        <translation>验证</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="314"/>
        <source>Username</source>
        <translation>用户名</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="315"/>
        <source>Password</source>
        <translation>密码</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="316"/>
        <source>Proxy Settings</source>
        <translation>代理设置</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="324"/>
        <source>No Printer Detected</source>
        <translation>未检测到打印设备</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="403"/>
        <source>Open to my default picture viewer</source>
        <translation>在默认图片浏览器中打开</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="404"/>
        <source>Save As</source>
        <translation>保存为</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="405"/>
        <source>Copy to clipboard</source>
        <translation>复制到剪贴板</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="261"/>
        <source>failed to open this file in your default image viewer.</source>
        <oldsource>Thumbnail Me failed to open this file in your default image viewer.</oldsource>
        <translation>无法用您的默认图片浏览器打开此缩略图。</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="278"/>
        <source>Save File</source>
        <translation>保存文件</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="304"/>
        <source>Saving the file failed</source>
        <translation>文件保存失败</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="101"/>
        <source>Progression:</source>
        <translation>进度 :</translation>
    </message>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="80"/>
        <source>Processing file %1 of %2: %3</source>
        <translation>文件转换中 %1 / %2: %3</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../main.cpp" line="92"/>
        <source>Initialisation</source>
        <translation>初始化</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="97"/>
        <source>Widgets initialisation</source>
        <translation>初始化</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="102"/>
        <source>Preferences reading</source>
        <translation>导入偏好设置</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="107"/>
        <source>Starting...</source>
        <translation>开始...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <location filename="../SettingsWidget.cpp" line="227"/>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>您的系统不包含OpenGL 3.0或更高版本。这个模块将被禁用。</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="233"/>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>您的系统不包含OpenGL。这个模块将被禁用。</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="340"/>
        <source>Settings</source>
        <translation>设置</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="341"/>
        <source>General</source>
        <translation>常规设置</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="342"/>
        <source>Fonts</source>
        <translation>字体</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="343"/>
        <source>Languages</source>
        <translation>语言</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="344"/>
        <source>Network</source>
        <translation>网络</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <location filename="../SuccessDialog.cpp" line="226"/>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;文件保存为:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="228"/>
        <source>Upload to ImageShack</source>
        <translation>上传至ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="232"/>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;文件保存为:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="234"/>
        <source>Upload these files to ImageShack</source>
        <translation>文件上传至ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="215"/>
        <source>Open Folder</source>
        <translation>打开文件夹</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="216"/>
        <source>Close</source>
        <translation>退出</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="116"/>
        <location filename="../ThumbnailEngine.cpp" line="126"/>
        <location filename="../ThumbnailEngine.cpp" line="143"/>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>无二进制MTN。操作取消。</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="117"/>
        <location filename="../ThumbnailEngine.cpp" line="127"/>
        <location filename="../ThumbnailEngine.cpp" line="144"/>
        <source>No fonts defined</source>
        <translation>无已定义字体</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="118"/>
        <source>Output path does not exist</source>
        <translation>目标文件夹不存在</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="119"/>
        <source>Select an output folder, please</source>
        <translation>请选择目标文件夹</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="130"/>
        <source>No file(s) loaded</source>
        <translation>无已导入文件</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="145"/>
        <source>No file selected</source>
        <translation>无已选择文件</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <location filename="../ThumbnailListwidget.cpp" line="105"/>
        <source>You must select a file to remove it from the list</source>
        <translation>您必须至少选择一个文件以便从列表中删除</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <location filename="../VerboseWindow.cpp" line="41"/>
        <location filename="../VerboseWindow.cpp" line="142"/>
        <source>Copy to clipboard</source>
        <translation>复制到剪贴板</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="141"/>
        <source>Logs</source>
        <translation>日志</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="38"/>
        <location filename="../VerboseWindow.cpp" line="143"/>
        <source>Clear all</source>
        <translation>清除全部</translation>
    </message>
</context>
</TS>
