<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="nl_NL" sourcelanguage="en_US">
<context>
    <name>About</name>
    <message>
        <location filename="../About.cpp" line="119"/>
        <source>About</source>
        <translation>Info over</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <location filename="../copyablelineedit.ui" line="84"/>
        <source>Copy to clipboard</source>
        <translation>Kopiëren naar klembord</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <location filename="../DockConf.cpp" line="361"/>
        <location filename="../DockConf.cpp" line="362"/>
        <source>Configuration</source>
        <translation>Configuratie</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="363"/>
        <source>Output Format</source>
        <translation>Uitvoer formaat</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="364"/>
        <source>Columns</source>
        <translation>Kolommen</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="365"/>
        <source>Rows</source>
        <translation>Rijen</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="366"/>
        <source>Width</source>
        <translation>Breedte</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="367"/>
        <source>Gap</source>
        <translation>Tussenruimte</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="368"/>
        <source>Quality</source>
        <translation>Kwaliteit</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="369"/>
        <source>Blank skip</source>
        <translation>Overslaan van blanco frames</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="370"/>
        <source>Edge detection</source>
        <translation>Randdetectie</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <location filename="../DockInputOutput.cpp" line="55"/>
        <location filename="../DockInputOutput.cpp" line="432"/>
        <source>Path Output</source>
        <translation>Uitvoerpad</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="70"/>
        <location filename="../DockInputOutput.cpp" line="434"/>
        <source>Same folder output as source</source>
        <translation>Uitvoerpad hetzelfde als bron</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="374"/>
        <source>Media list is already empty</source>
        <translation>Medialijst is al leeg</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="427"/>
        <source>Input and Output</source>
        <translation>Invoer en Uitvoer</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="428"/>
        <source>Load</source>
        <translation>Selecteren</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="429"/>
        <source>Reset</source>
        <translation>Opnieuw instellen</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="430"/>
        <source>Start</source>
        <translation>Start conversie</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="431"/>
        <source>Delete Selection</source>
        <translation>Verwijder selectie</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="433"/>
        <source>Preview selection file</source>
        <translation>Voorbeeld geselecteerd bestand</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <location filename="../DockStyles.cpp" line="527"/>
        <location filename="../DockStyles.cpp" line="528"/>
        <source>Styles</source>
        <translation>Opmaak</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="529"/>
        <source>Generated by Thumbnail me</source>
        <translation>Gegenereerd door Thumbnail me</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="530"/>
        <source>Info Text</source>
        <translation>Info tekst</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="531"/>
        <source>Timestamp</source>
        <translation>Tijdstempel</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="535"/>
        <location filename="../DockStyles.cpp" line="536"/>
        <source>Building Font Cache...</source>
        <translation>Opbouwen font cache...</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Left</source>
        <translation>Linksonder</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Right</source>
        <translation>Rechtsonder</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Right</source>
        <translation>Rechtsboven</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Left</source>
        <translation>Linksboven</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="532"/>
        <source>Additional Title</source>
        <translation>Aanvullende titel</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="533"/>
        <source>Background Color</source>
        <translation>Achtergrondkleur</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="534"/>
        <source>Shadow Color</source>
        <translation>Schaduwkleur</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <location filename="../DockTimeLine.cpp" line="185"/>
        <location filename="../DockTimeLine.cpp" line="192"/>
        <location filename="../DockTimeLine.cpp" line="206"/>
        <source>TimeLine</source>
        <translation>Tijdlijn</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="142"/>
        <location filename="../DockTimeLine.cpp" line="186"/>
        <location filename="../DockTimeLine.cpp" line="193"/>
        <location filename="../DockTimeLine.cpp" line="200"/>
        <location filename="../DockTimeLine.cpp" line="207"/>
        <source>From</source>
        <translation>Van</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="153"/>
        <location filename="../DockTimeLine.cpp" line="187"/>
        <location filename="../DockTimeLine.cpp" line="194"/>
        <location filename="../DockTimeLine.cpp" line="201"/>
        <location filename="../DockTimeLine.cpp" line="208"/>
        <source>To</source>
        <translation>Tot</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="188"/>
        <location filename="../DockTimeLine.cpp" line="195"/>
        <location filename="../DockTimeLine.cpp" line="202"/>
        <location filename="../DockTimeLine.cpp" line="209"/>
        <source>Total duration</source>
        <translation>Duur</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="131"/>
        <location filename="../DockTimeLine.cpp" line="199"/>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>Tijdlijn (Niet beschikbaar | Media wordt niet volledig ondersteund</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <location filename="../FontMapComboBox.cpp" line="132"/>
        <source>No fonts defined</source>
        <translation>Geen fonts gedefinieerd</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="197"/>
        <source>Add</source>
        <translation>Toevoegen</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="198"/>
        <source>Remove</source>
        <translation>Verwijder</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="87"/>
        <source>No fonts found in this folder</source>
        <translation>Geen fonts gevonden in deze map</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="81"/>
        <source>Select a font folder</source>
        <translation>Selecteer een font map</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="96"/>
        <source>You must select a path to remove it from the list</source>
        <translation>U moet een pad selecteren om het uit de lijst te verwijderen</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="239"/>
        <source>Never ask me to save my configuration on exit</source>
        <translation>Bij afsluiten nooit vragen om mijn configuratie op te slaan</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="240"/>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>Bij opstarten de laatste configuratie niet laden</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="241"/>
        <source>Background color of preview window</source>
        <translation>Achtergrondkleur van voorbeeld venster</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="242"/>
        <source>Output suffix:</source>
        <translation>Uitvoer achtervoegsel :</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="49"/>
        <location filename="../GeneralSettingsTab.cpp" line="243"/>
        <source>Activate openGL to preview thumbnails</source>
        <translation>Gebruik openGL om voorbeelden weer te geven</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="52"/>
        <location filename="../GeneralSettingsTab.cpp" line="244"/>
        <source>Animate pixmap while rendering</source>
        <translation>Animeer pixmap tijdens het renderen</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="238"/>
        <source>General Settings</source>
        <translation>Algemene instellingen</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <location filename="../HelpWidget.cpp" line="110"/>
        <source>Help</source>
        <translation>Hulp</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="426"/>
        <source>Password</source>
        <translation>Wachtwoord</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="427"/>
        <source>Remember Password</source>
        <translation>Wachtwoord onthouden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="55"/>
        <location filename="../ImageShackLoginWidget.cpp" line="429"/>
        <source>Login</source>
        <translation>Aanmelden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="87"/>
        <location filename="../ImageShackLoginWidget.cpp" line="430"/>
        <source>Login in progress...</source>
        <translation>U wordt aangemeld...</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="89"/>
        <location filename="../ImageShackLoginWidget.cpp" line="432"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="102"/>
        <location filename="../ImageShackLoginWidget.cpp" line="431"/>
        <source>Logout</source>
        <translation>Afmelden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="225"/>
        <source>Authentication failed. Check your username and password.</source>
        <translation>Authenticatie mislukt. Controleer uw gebruikersnaam en wachtwoord.</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="239"/>
        <source>Connection refused</source>
        <translation>Verbinding geweigerd</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="240"/>
        <source>Remote host closed</source>
        <translation>Remote host gesloten</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="241"/>
        <source>Host not found</source>
        <translation>Host niet gevonden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="242"/>
        <source>Timeout</source>
        <translation>Time-out</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="243"/>
        <source>Operation canceled</source>
        <translation>Bewerking geannuleerd</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="244"/>
        <source>SSL handshake failed</source>
        <translation>SSL handshake mislukt</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="245"/>
        <source>Proxy connection refused</source>
        <translation>Proxy verbinding geweigerd</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="246"/>
        <source>Proxy connection closed</source>
        <translation>Proxy verbinding gesloten</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="247"/>
        <source>Proxy not found</source>
        <translation>Proxy niet gevonden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="248"/>
        <source>Proxy timeout</source>
        <translation>Proxy time-out</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="249"/>
        <source>Proxy authentication required</source>
        <translation>Proxy authentificatie noodzakelijk</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="250"/>
        <source>Content access denied</source>
        <translation>Content toegang geweigerd</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="251"/>
        <source>Content operation not permitted</source>
        <translation>Content bewerking niet toegestaan</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="252"/>
        <source>Content not found</source>
        <translation>Content niet gevonden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="253"/>
        <source>Authentication required</source>
        <translation>Authentificatie noodzakelijk</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="254"/>
        <source>Protocol unknown</source>
        <translation>Protocol onbekend</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="255"/>
        <source>Protocol invalid operation</source>
        <translation>Protocol ongeldige bewerking</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="256"/>
        <source>Unknown network</source>
        <translation>Onbekend netwerk</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="257"/>
        <source>Unknown proxy</source>
        <translation>Onbekend proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="258"/>
        <source>Unknown content</source>
        <translation>Onbekende inhoud</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="259"/>
        <source>Protocol failure</source>
        <translation>Protocol fout</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="260"/>
        <source>Content resend</source>
        <translation>Content opnieuw verzenden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="261"/>
        <source>Temporary network failure</source>
        <translation>Tijdelijk netwerk storing</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="262"/>
        <location filename="../ImageShackLoginWidget.cpp" line="266"/>
        <source>Unknown error</source>
        <translation>Onbekende fout</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="263"/>
        <source>Failed to open the file</source>
        <translation>Openen van bestand niet gelukt</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="264"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Maximale grootte bereikt (5Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="270"/>
        <source>Upload Error:</source>
        <translation>Upload fout :</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="297"/>
        <source>Login as</source>
        <translation>Aanmelden als</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="425"/>
        <source>Username/E-mail</source>
        <translation>Gebruikersnaam/E-mail</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="428"/>
        <source>Autologin</source>
        <translation>Automatisch aanmelden</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="20"/>
        <source>Uploaded files</source>
        <translation>Geüploade bestanden</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="109"/>
        <source>File 1 of 1</source>
        <translation>Bestand 1 van 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="334"/>
        <source>Close</source>
        <translation>Sluiten</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="178"/>
        <source>Direct link</source>
        <translation>Directe link</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="179"/>
        <source>Short link</source>
        <translation>Korte link</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="180"/>
        <source>Hotlink for web</source>
        <translation>Hotlink voor web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="181"/>
        <source>Thumbnail for web</source>
        <translation>Thumbnail voor web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="182"/>
        <source>Thumbnail for forums 1</source>
        <translation>Thumbnail voor forums 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="183"/>
        <source>Thumbnail for forums 2</source>
        <translation>Thumbnail voor forums 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="184"/>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink voor forums 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="185"/>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink voor forums 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="100"/>
        <source>File %1 of %2</source>
        <translation>Bestand %1 van %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="30"/>
        <source>Log in to use this features</source>
        <translation>Log in om deze functies te gebruiken</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="136"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload modus: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anoniem&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="215"/>
        <location filename="../ImageShackUploadWidget.cpp" line="247"/>
        <source>File loaded: %1</source>
        <translation>Geladen bestand: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="299"/>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Formaat afbeelding wijzigen:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="310"/>
        <source>Do not resize</source>
        <translation>Formaat niet wijzigen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="315"/>
        <source>100x100 (avatar)</source>
        <translation>100x100 (avatar)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="320"/>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (thumbnail)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="325"/>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (voor websites en e-mail)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="330"/>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (voor message boards)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="335"/>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (12-inch beeldscherm)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="340"/>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (15-inch beeldscherm)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="345"/>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (19-inch beeldscherm)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="350"/>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (21-inch beeldscherm)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="361"/>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Privacy:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="371"/>
        <source>Private</source>
        <translation>Prive</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="381"/>
        <source>Public</source>
        <translation>Obenbaar</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="394"/>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Trefwoorden:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="423"/>
        <source>Comma separated list</source>
        <translation>Komma gescheiden lijst</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="459"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authenticatie is nodig om Privacy en Trefwoorden in te stellen op Uw thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Aanmelden&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="552"/>
        <source>Upload now</source>
        <translation>Upload nu</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="640"/>
        <source>Upload in progress...</source>
        <translation>Upload wordt uitgevoerd...</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="647"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="685"/>
        <source>File upload progress:</source>
        <translation>Bestand upload voortgang :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="709"/>
        <source>Total upload progress:</source>
        <translation>Totale upload voortgang :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="146"/>
        <source>File(s) loaded: %1</source>
        <translation>Bestand(en) geladen: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>Upload mode:</source>
        <translation>Upload modus :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <source>login</source>
        <translation>aanmelden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>anonymous</source>
        <translation>anoniem</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="212"/>
        <source>Log in to use these features</source>
        <translation>Log in om deze functies te gebruiken</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="229"/>
        <location filename="../ImageShackUploadWidget.cpp" line="272"/>
        <source>Processing file %1 of %2</source>
        <translation>Verwerken bestand %1 van %2</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="359"/>
        <source>Connection refused</source>
        <translation>Verbinding geweigerd</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="360"/>
        <source>Remote host closed</source>
        <translation>Remote host gesloten</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="361"/>
        <source>Host not found</source>
        <translation>Host niet gevonden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="362"/>
        <source>Timeout</source>
        <translation>Time-out</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="363"/>
        <source>Operation canceled</source>
        <translation>Bewerking geannuleerd</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="364"/>
        <source>SSL handshake failed</source>
        <translation>SSL handshake mislukt</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="365"/>
        <source>Proxy connection refused</source>
        <translation>Proxy verbinding geweigerd</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="366"/>
        <source>Proxy connection closed</source>
        <translation>Proxy verbinding gesloten</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="367"/>
        <source>Proxy not found</source>
        <translation>Proxy niet gevonden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="368"/>
        <source>Proxy timeout</source>
        <translation>Proxy time-out</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="369"/>
        <source>Proxy authentication required</source>
        <translation>Proxy authentificatie noodzakelijk</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="370"/>
        <source>Content access denied</source>
        <translation>Content toegang geweigerd</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="371"/>
        <source>Content operation not permitted</source>
        <translation>Content bewerking niet toegestaan</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="372"/>
        <source>Content not found</source>
        <translation>Content niet gevonden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="373"/>
        <source>Authentication required</source>
        <translation>Authentificatie noodzakelijk</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="374"/>
        <source>Protocol unknown</source>
        <translation>Protocol onbekend</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="375"/>
        <source>Protocol invalid operation</source>
        <translation>Protocol ongeldige bewerking</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="376"/>
        <source>Unknown network</source>
        <translation>Onbekend netwerk</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="377"/>
        <source>Unknown proxy</source>
        <translation>Onbekend proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="378"/>
        <source>Unknown content</source>
        <translation>Onbekende inhoud</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="379"/>
        <source>Protocol failure</source>
        <translation>Protocol fout</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="380"/>
        <source>Content resend</source>
        <translation>Content opnieuw verzenden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="381"/>
        <source>Temporary network failure</source>
        <translation>Tijdelijk netwerk storing</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="382"/>
        <location filename="../ImageShackUploadWidget.cpp" line="386"/>
        <source>Unknown error</source>
        <translation>Onbekende fout</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="383"/>
        <source>Failed to open the file</source>
        <translation>Openen van bestand niet gelukt</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="384"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Maximale grootte bereikt (5Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="391"/>
        <source>Upload Error:</source>
        <translation>Upload fout :</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <source>Open Configuration File</source>
        <translation>Open configuratiebestand</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Configuration file(*.ini)</source>
        <translation>Configuratiebestand(*.ini)</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="82"/>
        <location filename="../IniManager.cpp" line="219"/>
        <location filename="../IniManager.cpp" line="230"/>
        <location filename="../IniManager.cpp" line="241"/>
        <location filename="../IniManager.cpp" line="252"/>
        <location filename="../IniManager.cpp" line="335"/>
        <source>Configuration file loaded</source>
        <translation>Configuratiebestand geladen</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="85"/>
        <source>Incorrect settings file</source>
        <translation>Verkeerde instellingen bestand</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source>Configuration file</source>
        <translation>Configuratiebestand</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source> saved successfully</source>
        <translation>succesvol opgeslagen</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Save Configuration File</source>
        <translation>Opslaan configuratiebestand</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="274"/>
        <source>Not recent files</source>
        <translation>Niet recente bestanden</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="223"/>
        <source>English</source>
        <translation>Engels</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="224"/>
        <source>French</source>
        <translation>Frans</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="225"/>
        <source>Spanish</source>
        <translation>Spaans</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="226"/>
        <source>German</source>
        <translation>Duits</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="227"/>
        <source>Dutch</source>
        <translation>Nederlands</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="228"/>
        <source>Italian</source>
        <translation>Italiaans</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="229"/>
        <source>Czech</source>
        <translation>Tsjechisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="230"/>
        <source>Hungarian</source>
        <translation>Hongaars</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="231"/>
        <source>Croatian</source>
        <translation>Kroatisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="232"/>
        <source>Portuguese</source>
        <translation>Portugees</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="233"/>
        <source>Chinese</source>
        <translation>Chinees</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="234"/>
        <source>Russian</source>
        <translation>Russisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="222"/>
        <source>Select a language</source>
        <translation>Selecteer een taal</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="107"/>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>Can&apos;t see your language in this list?</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="108"/>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>Help us to translate</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="109"/>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>More information at</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../MainWindow.cpp" line="286"/>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>Laatste configuratie bestand kan niet worden geopend. De configuratie lay-out zal worden gereset.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="384"/>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>Wilt U de huidige configuratie opslaan voordat U Thumbnail me afsluit?</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="388"/>
        <source>saved successfully</source>
        <translation>succesvol opgeslagen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="480"/>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>bevat geen TrueType-lettertypen bestanden. Kies een andere lettertypen map in het menu Instellingen.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="553"/>
        <source>Toolbar</source>
        <translation>Werkbalk</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="555"/>
        <source>File</source>
        <translation>Bestand</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="556"/>
        <source>Edition</source>
        <translation>Editie</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="557"/>
        <source>View</source>
        <translation>Beeld</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="558"/>
        <source>Predefined Configuration</source>
        <translation>Voorgedefinieerde configuratie</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="559"/>
        <location filename="../MainWindow.cpp" line="576"/>
        <source>About</source>
        <translation>Info over</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="562"/>
        <source>Configuration</source>
        <translation>Configuratie</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="563"/>
        <source>Open</source>
        <translation>Openen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="564"/>
        <source>Import a configuration file</source>
        <translation>Importeer een configuratiebestand</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="565"/>
        <source>Import a recent configuration file</source>
        <translation>Importeer een recente configuratiebestand</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="566"/>
        <source>Save my current configuration</source>
        <translation>Bewaar mijn huidige configuratie</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="567"/>
        <source>Save my current configuration as</source>
        <translation>Bewaar mijn huidige configuratie als</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="568"/>
        <source>Print</source>
        <translation>Print</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="569"/>
        <source>Exit</source>
        <translation>Afsluiten</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="570"/>
        <source>Settings</source>
        <translation>Instellingen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="571"/>
        <source>Zoom in</source>
        <translation>Inzoomen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="572"/>
        <source>Zoom out</source>
        <translation>Uitzoomen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="573"/>
        <source>Clear all</source>
        <translation>Alles wissen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="574"/>
        <source>Fullscreen</source>
        <translation>Volledig scherm</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="575"/>
        <source>Help</source>
        <translation>Hulp</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="577"/>
        <source>About QT</source>
        <translation>Info over QT</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="578"/>
        <source>Donate</source>
        <translation>Doneer</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="579"/>
        <source>Website</source>
        <translation>Website</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="307"/>
        <source>Network Connection</source>
        <translation>Netwerk verbinding</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="308"/>
        <source>Direct connection</source>
        <translation>Directe verbinding</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="309"/>
        <source>Use proxy server</source>
        <translation>Gebruik proxy server</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="310"/>
        <source>Hostname</source>
        <translation>Hostnaam</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="311"/>
        <source>Port</source>
        <translation>Poort</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="312"/>
        <source>Type</source>
        <translation>Type</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="313"/>
        <source>Authentication</source>
        <translation>Authentificatie</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="314"/>
        <source>Username</source>
        <translation>Gebruikersnaam</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="315"/>
        <source>Password</source>
        <translation>Wachtwoord</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="316"/>
        <source>Proxy Settings</source>
        <translation>Proxy instellingen</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="324"/>
        <source>No Printer Detected</source>
        <translation>Geen printer gedetecteerd</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="403"/>
        <source>Open to my default picture viewer</source>
        <translation>Openen in mijn standaard foto-viewer</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="404"/>
        <source>Save As</source>
        <translation>Opslaan als</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="405"/>
        <source>Copy to clipboard</source>
        <translation>Kopiëren naar het klembord</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="261"/>
        <source>failed to open this file in your default image viewer.</source>
        <translation>niet gelukt om dit bestand te openen in Uw standaard foto-viewer.</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="278"/>
        <source>Save File</source>
        <translation>Opslaan bestand</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="304"/>
        <source>Saving the file failed</source>
        <translation>Opslaan van bestand mislukt</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="101"/>
        <source>Progression:</source>
        <translation>Voortgang :</translation>
    </message>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="80"/>
        <source>Processing file %1 of %2: %3</source>
        <translation>Verwerken bestand %1 van %2: %3</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../main.cpp" line="92"/>
        <source>Initialisation</source>
        <translation>Initialisatie</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="97"/>
        <source>Widgets initialisation</source>
        <translation>Widgets initialiseren</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="102"/>
        <source>Preferences reading</source>
        <translation>Voorkeuren inlezen</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="107"/>
        <source>Starting...</source>
        <translation>Starten...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <location filename="../SettingsWidget.cpp" line="227"/>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>OpenGL versie 3.0 of hoger is niet aanwezig op Uw systeem. Het zal worden uitgeschakeld.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="233"/>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>OpenGL niet gedetecteerd op Uw systeem. Het zal worden uitgeschakeld.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="340"/>
        <source>Settings</source>
        <translation>Instellingen</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="341"/>
        <source>General</source>
        <translation>Algemeen</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="342"/>
        <source>Fonts</source>
        <translation>Lettertypen</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="343"/>
        <source>Languages</source>
        <translation>Talen</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="344"/>
        <source>Network</source>
        <translation>Netwerk</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <location filename="../SuccessDialog.cpp" line="226"/>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Bestand opslaan als:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="228"/>
        <source>Upload to ImageShack</source>
        <translation>Upload naar ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="232"/>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Opslaan bestand(en) als:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="234"/>
        <source>Upload these files to ImageShack</source>
        <translation>Upload deze bestanden naar ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="215"/>
        <source>Open Folder</source>
        <translation>Open map</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="216"/>
        <source>Close</source>
        <translation>Sluit</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="116"/>
        <location filename="../ThumbnailEngine.cpp" line="126"/>
        <location filename="../ThumbnailEngine.cpp" line="143"/>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Mtn binary niet gevonden. Bewerking geannuleerd.</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="117"/>
        <location filename="../ThumbnailEngine.cpp" line="127"/>
        <location filename="../ThumbnailEngine.cpp" line="144"/>
        <source>No fonts defined</source>
        <translation>Geen lettertypen gedefinieerd</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="118"/>
        <source>Output path does not exist</source>
        <translation>Uitvoerpad bestaat niet</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="119"/>
        <source>Select an output folder, please</source>
        <translation>Selecteer a.u.b. een output map</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="130"/>
        <source>No file(s) loaded</source>
        <translation>Geen bestand(en) geselecteerd</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="145"/>
        <source>No file selected</source>
        <translation>Geen bestand geselecteerd</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <location filename="../ThumbnailListwidget.cpp" line="105"/>
        <source>You must select a file to remove it from the list</source>
        <translation>U moet een bestand selecteren om deze te verwijderen uit de lijst</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <location filename="../VerboseWindow.cpp" line="41"/>
        <location filename="../VerboseWindow.cpp" line="142"/>
        <source>Copy to clipboard</source>
        <translation>Kopiëren naar het klembord</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="141"/>
        <source>Logs</source>
        <translation>Logboeken</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="38"/>
        <location filename="../VerboseWindow.cpp" line="143"/>
        <source>Clear all</source>
        <translation>Verwijder alle</translation>
    </message>
</context>
</TS>
