<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="es_ES">
<context>
    <name>About</name>
    <message>
        <location filename="../About.cpp" line="119"/>
        <source>About</source>
        <translation>Acerca de</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <location filename="../copyablelineedit.ui" line="84"/>
        <source>Copy to clipboard</source>
        <translation>Copiar al portapapeles</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <location filename="../DockConf.cpp" line="361"/>
        <location filename="../DockConf.cpp" line="362"/>
        <source>Configuration</source>
        <translation>Configuración</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="363"/>
        <source>Output Format</source>
        <translation>Formato de Salida</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="364"/>
        <source>Columns</source>
        <translation>Columnas</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="365"/>
        <source>Rows</source>
        <translation>Filas</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="366"/>
        <source>Width</source>
        <translation>Ancho</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="367"/>
        <source>Gap</source>
        <translation>Margen</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="368"/>
        <source>Quality</source>
        <translation>Calidad</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="369"/>
        <source>Blank skip</source>
        <translation>Dejar en blanco</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="370"/>
        <source>Edge detection</source>
        <translation>Detección de ángulo</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <location filename="../DockInputOutput.cpp" line="55"/>
        <location filename="../DockInputOutput.cpp" line="432"/>
        <source>Path Output</source>
        <translation>Carpeta de Salida</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="70"/>
        <location filename="../DockInputOutput.cpp" line="434"/>
        <source>Same folder output as source</source>
        <translation>Misma carpeta de salida que de entrada</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="374"/>
        <source>Media list is already empty</source>
        <translation>La lista de archivos multimedia ya está vacía</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="427"/>
        <source>Input and Output</source>
        <translation>Entrada y Salida</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="428"/>
        <source>Load</source>
        <translation>Cargar</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="429"/>
        <source>Reset</source>
        <translation>Reset</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="430"/>
        <source>Start</source>
        <translation>Iniciar la conversión</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="431"/>
        <source>Delete Selection</source>
        <translation>Eliminar selección</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="433"/>
        <source>Preview selection file</source>
        <translation>Previsualizar el fichero seleccionado</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <location filename="../DockStyles.cpp" line="527"/>
        <location filename="../DockStyles.cpp" line="528"/>
        <source>Styles</source>
        <translation>Estilos</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="529"/>
        <source>Generated by Thumbnail me</source>
        <translation>Generado por Thumbnail me</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="530"/>
        <source>Info Text</source>
        <translation>Detalles Técnicos</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="531"/>
        <source>Timestamp</source>
        <translation>Fecha</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="535"/>
        <location filename="../DockStyles.cpp" line="536"/>
        <source>Building Font Cache...</source>
        <translation>Creando caché de fuentes...</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Left</source>
        <translation>Abajo-Izquierda</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Right</source>
        <translation>Abajo-Derecha</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Right</source>
        <translation>Arriba-Derecha</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Left</source>
        <translation>Arriba-Izquierda</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="532"/>
        <source>Additional Title</source>
        <translation>Título Adicional</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="533"/>
        <source>Background Color</source>
        <translation>Color de fondo</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="534"/>
        <source>Shadow Color</source>
        <translation>Color de sombra</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <location filename="../DockTimeLine.cpp" line="185"/>
        <location filename="../DockTimeLine.cpp" line="192"/>
        <location filename="../DockTimeLine.cpp" line="206"/>
        <source>TimeLine</source>
        <translation>Timeline</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="142"/>
        <location filename="../DockTimeLine.cpp" line="186"/>
        <location filename="../DockTimeLine.cpp" line="193"/>
        <location filename="../DockTimeLine.cpp" line="200"/>
        <location filename="../DockTimeLine.cpp" line="207"/>
        <source>From</source>
        <translation>Desde</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="153"/>
        <location filename="../DockTimeLine.cpp" line="187"/>
        <location filename="../DockTimeLine.cpp" line="194"/>
        <location filename="../DockTimeLine.cpp" line="201"/>
        <location filename="../DockTimeLine.cpp" line="208"/>
        <source>To</source>
        <translation>Hacia</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="188"/>
        <location filename="../DockTimeLine.cpp" line="195"/>
        <location filename="../DockTimeLine.cpp" line="202"/>
        <location filename="../DockTimeLine.cpp" line="209"/>
        <source>Total duration</source>
        <translation>Duración total</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="131"/>
        <location filename="../DockTimeLine.cpp" line="199"/>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>TimeLine (No disponible) | Media no soportada</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <location filename="../FontMapComboBox.cpp" line="132"/>
        <source>No fonts defined</source>
        <translation>No hay fuentes definidas</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="197"/>
        <source>Add</source>
        <translation>Añadir</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="198"/>
        <source>Remove</source>
        <translation>Eliminar</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="87"/>
        <source>No fonts found in this folder</source>
        <translation>No se encontraron fuentes in esta carpeta</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="81"/>
        <source>Select a font folder</source>
        <translation>Seleccione una carpeta de fuentes</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="96"/>
        <source>You must select a path to remove it from the list</source>
        <translation>Debes elegir una ruta a eliminar de la lista</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="239"/>
        <source>Never ask me to save my configuration on exit</source>
        <translation>No volver a preguntar si quiero guardar mi configuración al salir</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="240"/>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>No cargar la última configuración en el arranque</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="241"/>
        <source>Background color of preview window</source>
        <translation>Color de fondo de la ventana de previsualización</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="242"/>
        <source>Output suffix:</source>
        <translation>Extensión de salida :</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="49"/>
        <location filename="../GeneralSettingsTab.cpp" line="243"/>
        <source>Activate openGL to preview thumbnails</source>
        <translation>Activar openGL para previsualizar los thumnails</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="52"/>
        <location filename="../GeneralSettingsTab.cpp" line="244"/>
        <source>Animate pixmap while rendering</source>
        <translation>Activar la animación del thumbnail</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="238"/>
        <source>General Settings</source>
        <translation>Parámetros generales</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <location filename="../HelpWidget.cpp" line="110"/>
        <source>Help</source>
        <translation>Ayuda</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="426"/>
        <source>Password</source>
        <translation>Contraseña</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="427"/>
        <source>Remember Password</source>
        <translation>Recordar contraseña</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="55"/>
        <location filename="../ImageShackLoginWidget.cpp" line="429"/>
        <source>Login</source>
        <translation>Iniciar sesión</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="87"/>
        <location filename="../ImageShackLoginWidget.cpp" line="430"/>
        <source>Login in progress...</source>
        <translation>Autenticación en progreso...</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="89"/>
        <location filename="../ImageShackLoginWidget.cpp" line="432"/>
        <source>Cancel</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="225"/>
        <source>Authentication failed. Check your username and password.</source>
        <translation>Fallo en la autenticación. Revise su nombre d usuario y contraseña.</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="239"/>
        <source>Connection refused</source>
        <translation>Conexión rechazada</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="240"/>
        <source>Remote host closed</source>
        <translation>Clienter remoto no disponible</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="241"/>
        <source>Host not found</source>
        <translation>Cliente no encontrado</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="242"/>
        <source>Timeout</source>
        <translation>Tiempo transcurrido</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="243"/>
        <source>Operation canceled</source>
        <translation>Operación cancelada</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="244"/>
        <source>SSL handshake failed</source>
        <translation>Fallo en la inicialización  SSL</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="245"/>
        <source>Proxy connection refused</source>
        <translation>Conexión al proxy rechazada</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="246"/>
        <source>Proxy connection closed</source>
        <translation>Conexión al proxy terminada</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="247"/>
        <source>Proxy not found</source>
        <translation>Proxy no encontrado</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="248"/>
        <source>Proxy timeout</source>
        <translation>Tiempo de conexión al proxy agotado</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="249"/>
        <source>Proxy authentication required</source>
        <translation>Se requiere autenticación en el proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="250"/>
        <source>Content access denied</source>
        <translation>Acceso al contenido denegado</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="251"/>
        <source>Content operation not permitted</source>
        <translation>Operación sobre el contenido no permitida</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="252"/>
        <source>Content not found</source>
        <translation>Contenido no encontrado</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="253"/>
        <source>Authentication required</source>
        <translation>Autenticación requerida</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="254"/>
        <source>Protocol unknown</source>
        <translation>Protocolo desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="255"/>
        <source>Protocol invalid operation</source>
        <translation>Operación de protoclo no válida</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="256"/>
        <source>Unknown network</source>
        <translation>Red desconocida</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="257"/>
        <source>Unknown proxy</source>
        <translation>Proxy desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="258"/>
        <source>Unknown content</source>
        <translation>Contenido desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="259"/>
        <source>Protocol failure</source>
        <translation>Fallo del protocolo</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="260"/>
        <source>Content resend</source>
        <translation>Reenvío del contenido</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="261"/>
        <source>Temporary network failure</source>
        <translation>Fallo temporal de la red</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="262"/>
        <location filename="../ImageShackLoginWidget.cpp" line="266"/>
        <source>Unknown error</source>
        <translation>Error desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="263"/>
        <source>Failed to open the file</source>
        <translation>Fallo al abrir el archivo</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="264"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Máximo tamaño alcanzado (5Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="270"/>
        <source>Upload Error:</source>
        <translation>Error de subida :</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="297"/>
        <source>Login as</source>
        <translation>Iniciar sesión como</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="425"/>
        <source>Username/E-mail</source>
        <translation>Nombre de usuario/E-mail</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="428"/>
        <source>Autologin</source>
        <translation>Autenticación Automática</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="102"/>
        <location filename="../ImageShackLoginWidget.cpp" line="431"/>
        <source>Logout</source>
        <translation>Cerrar sesión</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="20"/>
        <source>Uploaded files</source>
        <translation>Ficheros subidos</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="109"/>
        <source>File 1 of 1</source>
        <translation>Fichero 1 de 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="334"/>
        <source>Close</source>
        <translation>Cerrar</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="178"/>
        <source>Direct link</source>
        <translation>Enlace Directo</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="179"/>
        <source>Short link</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="180"/>
        <source>Hotlink for web</source>
        <translation>Hotlink para web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="181"/>
        <source>Thumbnail for web</source>
        <translation>Thumbnail para la web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="182"/>
        <source>Thumbnail for forums 1</source>
        <translation>Thumbnail para foros 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="183"/>
        <source>Thumbnail for forums 2</source>
        <translation>Thumbnail para foros 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="184"/>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink para foros 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="185"/>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink para foros 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="100"/>
        <source>File %1 of %2</source>
        <translation>Fichero %1 de %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>Upload mode:</source>
        <translation>Modo de subida :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="136"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Modo de subida: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anónimo&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="215"/>
        <location filename="../ImageShackUploadWidget.cpp" line="247"/>
        <source>File loaded: %1</source>
        <translation>Fichero cargado: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="299"/>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Modificar el tamaño de la imagen:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="310"/>
        <source>Do not resize</source>
        <translation>No reducir tamaño</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="315"/>
        <source>100x100 (avatar)</source>
        <translation>100x100 (avatar)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="320"/>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (thumbnail)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="325"/>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (para sitios web y e-maill)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="330"/>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (para mensajes por pantalla)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="335"/>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (monitor de 12 pulgadas)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="340"/>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (monitor de 15 pulgadas)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="345"/>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (monitor de 19 pulgadas)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="350"/>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (monitor de 21 pulgadas)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="423"/>
        <source>Comma separated list</source>
        <translation>Separe la lista con comas</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="640"/>
        <source>Upload in progress...</source>
        <translation>Subida en curso...</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="361"/>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Privacidad:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="371"/>
        <source>Private</source>
        <translation>Privado</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="381"/>
        <source>Public</source>
        <translation>Público</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="394"/>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="459"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Autenticación requerida para modificar la privacidad y las etiquetas de su thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Ingresar&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="552"/>
        <source>Upload now</source>
        <translation>Subir ahora</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="647"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="685"/>
        <source>File upload progress:</source>
        <translation>File Upload progress :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="709"/>
        <source>Total upload progress:</source>
        <translation>Progreso de subida :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="146"/>
        <source>File(s) loaded: %1</source>
        <translation>Archivo(s) subido(s): %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <source>login</source>
        <translation>Inicio de sesión</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>anonymous</source>
        <translation>anónimo</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="30"/>
        <source>Log in to use this features</source>
        <translation>Inicie sesión para utilizar esta característica</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="212"/>
        <source>Log in to use these features</source>
        <translation>Inicie sesión para utilizar estas características</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="229"/>
        <location filename="../ImageShackUploadWidget.cpp" line="272"/>
        <source>Processing file %1 of %2</source>
        <translation>Procesando fichero %1 de %2</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="359"/>
        <source>Connection refused</source>
        <translation>Conexión rechazada</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="360"/>
        <source>Remote host closed</source>
        <translation>Clienter remoto no disponible</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="361"/>
        <source>Host not found</source>
        <translation>Cliente no encontrado</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="362"/>
        <source>Timeout</source>
        <translation>Tiempo transcurrido</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="363"/>
        <source>Operation canceled</source>
        <translation>Operación cancelada</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="364"/>
        <source>SSL handshake failed</source>
        <translation>Fallo en la inicialización  SSL</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="365"/>
        <source>Proxy connection refused</source>
        <translation>Conexión al proxy rechazada</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="366"/>
        <source>Proxy connection closed</source>
        <translation>Conexión al proxy terminada</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="367"/>
        <source>Proxy not found</source>
        <translation>Proxy no encontrado</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="368"/>
        <source>Proxy timeout</source>
        <translation>Tiempo de conexión al proxy agotado</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="369"/>
        <source>Proxy authentication required</source>
        <translation>Se requiere autenticación en el proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="370"/>
        <source>Content access denied</source>
        <translation>Acceso al contenido denegado</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="371"/>
        <source>Content operation not permitted</source>
        <translation>Operación sobre el contenido no permitida</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="372"/>
        <source>Content not found</source>
        <translation>Contenido no encontrado</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="373"/>
        <source>Authentication required</source>
        <translation>Autenticación requerida</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="374"/>
        <source>Protocol unknown</source>
        <translation>Protocolo desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="375"/>
        <source>Protocol invalid operation</source>
        <translation>Operación de protoclo no válida</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="376"/>
        <source>Unknown network</source>
        <translation>Red desconocida</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="377"/>
        <source>Unknown proxy</source>
        <translation>Proxy desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="378"/>
        <source>Unknown content</source>
        <translation>Contenido desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="379"/>
        <source>Protocol failure</source>
        <translation>Fallo del protocolo</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="380"/>
        <source>Content resend</source>
        <translation>Reenvío del contenido</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="381"/>
        <source>Temporary network failure</source>
        <translation>Fallo temporal de la red</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="382"/>
        <location filename="../ImageShackUploadWidget.cpp" line="386"/>
        <source>Unknown error</source>
        <translation>Error desconocido</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="383"/>
        <source>Failed to open the file</source>
        <translation>Fallo al abrir el archivo</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="384"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Máximo tamaño alcanzado (5Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="391"/>
        <source>Upload Error:</source>
        <translation>Error de subida :</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <source>Open Configuration File</source>
        <translation>Abrir el Fichero de Configuración</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Configuration file(*.ini)</source>
        <translation>Fichero de Configuración(*.ini)</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="82"/>
        <location filename="../IniManager.cpp" line="219"/>
        <location filename="../IniManager.cpp" line="230"/>
        <location filename="../IniManager.cpp" line="241"/>
        <location filename="../IniManager.cpp" line="252"/>
        <location filename="../IniManager.cpp" line="335"/>
        <source>Configuration file loaded</source>
        <translation>Fichero de Configuración caragado</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="85"/>
        <source>Incorrect settings file</source>
        <translation>Fichero de configuración incorrecto</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source>Configuration file</source>
        <translation>Fichero de Configuración</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source> saved successfully</source>
        <translation>Guardado correctamente</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Save Configuration File</source>
        <translation>Guardar el Fichero de Configuración</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="274"/>
        <source>Not recent files</source>
        <translation>No hay ficheros recientes</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="223"/>
        <source>English</source>
        <translation>Inglés</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="224"/>
        <source>French</source>
        <translation>Francés</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="225"/>
        <source>Spanish</source>
        <translation>Español</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="226"/>
        <source>German</source>
        <translation>Alemán</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="227"/>
        <source>Dutch</source>
        <translation>Holandés</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="228"/>
        <source>Italian</source>
        <translation>Italiano</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="229"/>
        <source>Czech</source>
        <translatorcomment>Hollandais</translatorcomment>
        <translation>Checo</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="230"/>
        <source>Hungarian</source>
        <translation>Húngaro</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="231"/>
        <source>Croatian</source>
        <translation>Croata</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="232"/>
        <source>Portuguese</source>
        <translation>Portugués</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="233"/>
        <source>Chinese</source>
        <translation>Chino</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="234"/>
        <source>Russian</source>
        <translation>Ruso</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="109"/>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="222"/>
        <source>Select a language</source>
        <translation>Seleccione un idioma</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="107"/>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="108"/>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../MainWindow.cpp" line="286"/>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>La última configuración no pudo ser abierta. Se establecera la configuración por defecto.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="384"/>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>¿Quiere guardar la configuración actual antes de salir de Thumbnail me?</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="388"/>
        <source>saved successfully</source>
        <translation>guardado correctamente</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="480"/>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>no contiene archivos de fuentes válidos. Por favor, seleccione otra carpeta de fuentes en el Menú de Ajustes.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="553"/>
        <source>Toolbar</source>
        <translation>Barra de Herramientas</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="555"/>
        <source>File</source>
        <translation>Archivo</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="556"/>
        <source>Edition</source>
        <translation>Edición</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="557"/>
        <source>View</source>
        <translation>Ver</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="558"/>
        <source>Predefined Configuration</source>
        <translation>Configuración predeterminada</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="559"/>
        <location filename="../MainWindow.cpp" line="576"/>
        <source>About</source>
        <translation>Acerca de</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="562"/>
        <source>Configuration</source>
        <translation>Configuración</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="563"/>
        <source>Open</source>
        <translation>Abrir</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="564"/>
        <source>Import a configuration file</source>
        <translation>Importar un fichero de configuración</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="565"/>
        <source>Import a recent configuration file</source>
        <translation>Importar un archivo de configuración reciente</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="566"/>
        <source>Save my current configuration</source>
        <translation>Guardar mi configuración actual</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="567"/>
        <source>Save my current configuration as</source>
        <translation>Guardar mi configuración actual como</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="568"/>
        <source>Print</source>
        <translation>Imprimir</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="569"/>
        <source>Exit</source>
        <translation>Salir</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="570"/>
        <source>Settings</source>
        <translation>Parámetros</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="571"/>
        <source>Zoom in</source>
        <translation>Acercar</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="572"/>
        <source>Zoom out</source>
        <translation>Alejar</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="573"/>
        <source>Clear all</source>
        <translation>Borrar todo</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="574"/>
        <source>Fullscreen</source>
        <translation>Pantalla completa</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="575"/>
        <source>Help</source>
        <translation>Ayuda</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="577"/>
        <source>About QT</source>
        <translation>Acerca de QT</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="578"/>
        <source>Donate</source>
        <translation>Hacer una donación</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="579"/>
        <source>Website</source>
        <translation>Sitio web</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="307"/>
        <source>Network Connection</source>
        <translation>Conexión de red</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="308"/>
        <source>Direct connection</source>
        <translation>Conexión directa</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="309"/>
        <source>Use proxy server</source>
        <translation>Usar servidor proxy</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="310"/>
        <source>Hostname</source>
        <translation>Nombre del cliente</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="311"/>
        <source>Port</source>
        <translation>Puerto</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="312"/>
        <source>Type</source>
        <translation>Tipo</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="313"/>
        <source>Authentication</source>
        <translation>Autenticación</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="314"/>
        <source>Username</source>
        <translation>Nombre de usuario</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="315"/>
        <source>Password</source>
        <translation>Contraseña</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="316"/>
        <source>Proxy Settings</source>
        <translation>Parámetros del proxy</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="324"/>
        <source>No Printer Detected</source>
        <translation>No hay impresora detectada</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="403"/>
        <source>Open to my default picture viewer</source>
        <translation>Abrir mi visor de imágenes por defecto</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="404"/>
        <source>Save As</source>
        <translation>Guardar como</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="405"/>
        <source>Copy to clipboard</source>
        <translation>Copiar al portapapeles</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="261"/>
        <source>failed to open this file in your default image viewer.</source>
        <translation>fallo al abrir el archivo en su visor de imágenes por defecto.</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="278"/>
        <source>Save File</source>
        <translation>Guardar fichero</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="304"/>
        <source>Saving the file failed</source>
        <translation>Fallo al guardar el fichero</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="101"/>
        <source>Progression:</source>
        <translation>Progreso :</translation>
    </message>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="80"/>
        <source>Processing file %1 of %2: %3</source>
        <translation>Procesando fichero: %1 de %2: %3</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../main.cpp" line="92"/>
        <source>Initialisation</source>
        <translation>Inicialización</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="97"/>
        <source>Widgets initialisation</source>
        <translation>Instalación de Widgets</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="102"/>
        <source>Preferences reading</source>
        <translation>Leyendo preferencias</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="107"/>
        <source>Starting...</source>
        <translation>Inicializando...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <location filename="../SettingsWidget.cpp" line="227"/>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>Versión OpenGL 3.0 o superior no está en el sistema. Será con discapacidad.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="233"/>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>openGL no detectado en su sistema. Será con discapacidad.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="340"/>
        <source>Settings</source>
        <translation>Parámetros</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="341"/>
        <source>General</source>
        <translation>General</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="342"/>
        <source>Fonts</source>
        <translation>Fuentes</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="343"/>
        <source>Languages</source>
        <translation>Idiomas</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="344"/>
        <source>Network</source>
        <translation>Red</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <location filename="../SuccessDialog.cpp" line="226"/>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Guardar fichero como:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="228"/>
        <source>Upload to ImageShack</source>
        <translation>Subir a ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="232"/>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Guardar archivo(s) como:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="234"/>
        <source>Upload these files to ImageShack</source>
        <translation>Subir estos ficheros a ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="215"/>
        <source>Open Folder</source>
        <translation>Abrir Carpeta</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="216"/>
        <source>Close</source>
        <translation>Cerrar</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="116"/>
        <location filename="../ThumbnailEngine.cpp" line="126"/>
        <location filename="../ThumbnailEngine.cpp" line="143"/>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Mtn binario no encontrado. Operación cancelada.</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="117"/>
        <location filename="../ThumbnailEngine.cpp" line="127"/>
        <location filename="../ThumbnailEngine.cpp" line="144"/>
        <source>No fonts defined</source>
        <translation>No hay fuentes definidas</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="118"/>
        <source>Output path does not exist</source>
        <translation>La ruta de salida no existe</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="119"/>
        <source>Select an output folder, please</source>
        <translation>Seleccione una carpeta de salida, por favor</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="130"/>
        <source>No file(s) loaded</source>
        <translation>No se cargaron los archivos</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="145"/>
        <source>No file selected</source>
        <translation>No hay ficheros seleccionados</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <location filename="../ThumbnailListwidget.cpp" line="105"/>
        <source>You must select a file to remove it from the list</source>
        <translation>Debes seleccionar el fichero a eliminar de la lista</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <location filename="../VerboseWindow.cpp" line="41"/>
        <location filename="../VerboseWindow.cpp" line="142"/>
        <source>Copy to clipboard</source>
        <translation>Copiar al portapapeles</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="141"/>
        <source>Logs</source>
        <translation>Registros</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="38"/>
        <location filename="../VerboseWindow.cpp" line="143"/>
        <source>Clear all</source>
        <translation>Eliminar todo</translation>
    </message>
</context>
</TS>
