<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="de_DE">
<context>
    <name>About</name>
    <message>
        <location filename="../About.cpp" line="119"/>
        <source>About</source>
        <translation>Über Thumbnail me</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <location filename="../copyablelineedit.ui" line="84"/>
        <source>Copy to clipboard</source>
        <translation>In Zwischenablage kopieren</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <location filename="../DockConf.cpp" line="361"/>
        <location filename="../DockConf.cpp" line="362"/>
        <source>Configuration</source>
        <translation>Konfiguration</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="363"/>
        <source>Output Format</source>
        <translation>Ausgabeformat</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="364"/>
        <source>Columns</source>
        <translation>Spalten</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="365"/>
        <source>Rows</source>
        <translation>Zeilen</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="366"/>
        <source>Width</source>
        <translation>Breite</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="367"/>
        <source>Gap</source>
        <translation>Abstand</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="368"/>
        <source>Quality</source>
        <translation>Qualität</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="369"/>
        <source>Blank skip</source>
        <translation>Leere Start/End-Frames überspringen</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="370"/>
        <source>Edge detection</source>
        <translation>Kanten erkennen</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <location filename="../DockInputOutput.cpp" line="55"/>
        <location filename="../DockInputOutput.cpp" line="432"/>
        <source>Path Output</source>
        <translation>Ausgabepfad</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="70"/>
        <location filename="../DockInputOutput.cpp" line="434"/>
        <source>Same folder output as source</source>
        <translation>Im selben Ordner als  originales Datei speichern</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="374"/>
        <source>Media list is already empty</source>
        <translation>Wiedergabeliste schon geleert</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="427"/>
        <source>Input and Output</source>
        <translation>Eingabe und Ausgabe</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="428"/>
        <source>Load</source>
        <translation>Datei(en) öffnen</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="429"/>
        <source>Reset</source>
        <translation>Zurücksetzen</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="430"/>
        <source>Start</source>
        <translation>Konvertieren</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="431"/>
        <source>Delete Selection</source>
        <translation>Auswahl löschen</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="433"/>
        <source>Preview selection file</source>
        <translation>Vorschau</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <location filename="../DockStyles.cpp" line="527"/>
        <location filename="../DockStyles.cpp" line="528"/>
        <source>Styles</source>
        <translation>Style</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="529"/>
        <source>Generated by Thumbnail me</source>
        <translation>Generiert durch Thumbnail me</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="530"/>
        <source>Info Text</source>
        <translation>Info Text</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="531"/>
        <source>Timestamp</source>
        <translation>Laufzeitanzeige</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="535"/>
        <location filename="../DockStyles.cpp" line="536"/>
        <source>Building Font Cache...</source>
        <translation>Laden der Font-Cache...</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Left</source>
        <translation>Unten Links</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Right</source>
        <translation>Unten Rechts</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Right</source>
        <translation>Oben Rechts</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Left</source>
        <translation>Oben Links</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="532"/>
        <source>Additional Title</source>
        <translation>Zusätzliche Titelzeile</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="533"/>
        <source>Background Color</source>
        <translation>Hintergrundfarbe</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="534"/>
        <source>Shadow Color</source>
        <translation>Schattenfarbe</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <location filename="../DockTimeLine.cpp" line="185"/>
        <location filename="../DockTimeLine.cpp" line="192"/>
        <location filename="../DockTimeLine.cpp" line="206"/>
        <source>TimeLine</source>
        <translation>Zeitlinie</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="142"/>
        <location filename="../DockTimeLine.cpp" line="186"/>
        <location filename="../DockTimeLine.cpp" line="193"/>
        <location filename="../DockTimeLine.cpp" line="200"/>
        <location filename="../DockTimeLine.cpp" line="207"/>
        <source>From</source>
        <translation>Von</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="153"/>
        <location filename="../DockTimeLine.cpp" line="187"/>
        <location filename="../DockTimeLine.cpp" line="194"/>
        <location filename="../DockTimeLine.cpp" line="201"/>
        <location filename="../DockTimeLine.cpp" line="208"/>
        <source>To</source>
        <translation>Bis</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="188"/>
        <location filename="../DockTimeLine.cpp" line="195"/>
        <location filename="../DockTimeLine.cpp" line="202"/>
        <location filename="../DockTimeLine.cpp" line="209"/>
        <source>Total duration</source>
        <translation>Gesamtdauer</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="131"/>
        <location filename="../DockTimeLine.cpp" line="199"/>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>Zeitlinie (nicht verfügbar) | Unbekanntes Format</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <location filename="../FontMapComboBox.cpp" line="132"/>
        <source>No fonts defined</source>
        <translation>Keine Fonts definiert</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="197"/>
        <source>Add</source>
        <translation>Hinzufügen</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="198"/>
        <source>Remove</source>
        <translation>Entfernen</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="87"/>
        <source>No fonts found in this folder</source>
        <translation>Keine Fonts in diesem Verzeichnis gefunden</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="81"/>
        <source>Select a font folder</source>
        <translation>Ein Font-Verzeichnis wählen</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="96"/>
        <source>You must select a path to remove it from the list</source>
        <translation>Ein Pfad muss ausgewählt sein um ihn zu entfernen</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="239"/>
        <source>Never ask me to save my configuration on exit</source>
        <translation>Nicht nachfragen, ob Konfiguration beim Verlassen gespeichert werden soll</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="240"/>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>Bei Start letzte Konfiguration nicht laden</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="241"/>
        <source>Background color of preview window</source>
        <translation>Hintergrundfarbe des Vorschaufensters</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="242"/>
        <source>Output suffix:</source>
        <translation>Ausgabesuffix :</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="49"/>
        <location filename="../GeneralSettingsTab.cpp" line="243"/>
        <source>Activate openGL to preview thumbnails</source>
        <translation>OpenGL für Thumbnail-Vorschau aktivieren</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="52"/>
        <location filename="../GeneralSettingsTab.cpp" line="244"/>
        <source>Animate pixmap while rendering</source>
        <translation>Pixmap animieren während des Renderns</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="238"/>
        <source>General Settings</source>
        <translation>Allgemeine Einstellungen</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <location filename="../HelpWidget.cpp" line="110"/>
        <source>Help</source>
        <translation>Hilfe</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="426"/>
        <source>Password</source>
        <translation>Passwort</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="427"/>
        <source>Remember Password</source>
        <translation>Passwort speichern</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="55"/>
        <location filename="../ImageShackLoginWidget.cpp" line="429"/>
        <source>Login</source>
        <translation>Anmelden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="87"/>
        <location filename="../ImageShackLoginWidget.cpp" line="430"/>
        <source>Login in progress...</source>
        <translation>Anmeldung...</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="89"/>
        <location filename="../ImageShackLoginWidget.cpp" line="432"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="225"/>
        <source>Authentication failed. Check your username and password.</source>
        <translation>Anmeldung fehlgeschlagen. Bitte Usernamen und Passwort überprüfen.</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="239"/>
        <source>Connection refused</source>
        <translation>Verbindung verweigert</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="240"/>
        <source>Remote host closed</source>
        <translation>Gegenseite geschlossen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="241"/>
        <source>Host not found</source>
        <translation>Host nicht gefunden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="242"/>
        <source>Timeout</source>
        <translation>Timeout</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="243"/>
        <source>Operation canceled</source>
        <translation>Vorgang abgebrochen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="244"/>
        <source>SSL handshake failed</source>
        <translation>SSL handshake gescheitert</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="245"/>
        <source>Proxy connection refused</source>
        <translation>Proxy hat Verbindung verweigert</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="246"/>
        <source>Proxy connection closed</source>
        <translation>Proxy-Verbindung geschlossen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="247"/>
        <source>Proxy not found</source>
        <translation>Proxy nicht gefunden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="248"/>
        <source>Proxy timeout</source>
        <translation>Proxy timeout</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="249"/>
        <source>Proxy authentication required</source>
        <translation>Proxy benötigt Authentifizierung</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="250"/>
        <source>Content access denied</source>
        <translation>Zugriff verweigert</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="251"/>
        <source>Content operation not permitted</source>
        <translation>Unerlaubter Vorgang</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="252"/>
        <source>Content not found</source>
        <translation>Inhalte nicht gefunden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="253"/>
        <source>Authentication required</source>
        <translation>Authentifizierung notwendig</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="254"/>
        <source>Protocol unknown</source>
        <translation>Unbekanntes Protokoll</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="255"/>
        <source>Protocol invalid operation</source>
        <translation>Fehlerhaftes Protokoll</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="256"/>
        <source>Unknown network</source>
        <translation>Unbekanntes Netzwerk</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="257"/>
        <source>Unknown proxy</source>
        <translation>Unbekannter Proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="258"/>
        <source>Unknown content</source>
        <translation>Unbekannte Inhalte</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="259"/>
        <source>Protocol failure</source>
        <translation>Protokoll gescheitert</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="260"/>
        <source>Content resend</source>
        <translation>Inhalt erneut gesandt</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="261"/>
        <source>Temporary network failure</source>
        <translation>Temporärer Netzwerkfehler</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="262"/>
        <location filename="../ImageShackLoginWidget.cpp" line="266"/>
        <source>Unknown error</source>
        <translation>Unbekannter Fehler</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="263"/>
        <source>Failed to open the file</source>
        <translation>Datei konnte nicht geöffnet werden</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="264"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Maximale Dateigröße (5Mb) erreicht</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="270"/>
        <source>Upload Error:</source>
        <translation>Fehler beim Hochladen :</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="297"/>
        <source>Login as</source>
        <translation>Anmelden als</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="425"/>
        <source>Username/E-mail</source>
        <translation>Username/E-Mail</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="428"/>
        <source>Autologin</source>
        <translation>Automatisch einloggen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="102"/>
        <location filename="../ImageShackLoginWidget.cpp" line="431"/>
        <source>Logout</source>
        <translation>Abmelden</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="20"/>
        <source>Uploaded files</source>
        <translation>Hochgeladene Dateien</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="109"/>
        <source>File 1 of 1</source>
        <translation>Datei 1 von 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="334"/>
        <source>Close</source>
        <translation>Schliessen</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="178"/>
        <source>Direct link</source>
        <translation>Direkt Link</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="179"/>
        <source>Short link</source>
        <translation>Kurzer Link</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="180"/>
        <source>Hotlink for web</source>
        <translation>Hotlink für Web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="181"/>
        <source>Thumbnail for web</source>
        <translation>Thumbnail für Web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="182"/>
        <source>Thumbnail for forums 1</source>
        <translation>Thumbnail für Foren 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="183"/>
        <source>Thumbnail for forums 2</source>
        <translation>Thumbnail für Foren 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="184"/>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink für Foren 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="185"/>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink für Foren 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="100"/>
        <source>File %1 of %2</source>
        <translation>Datei %1 von %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>Upload mode:</source>
        <translation>Uploadmodus :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="136"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Uploadmodus: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonym&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="215"/>
        <location filename="../ImageShackUploadWidget.cpp" line="247"/>
        <source>File loaded: %1</source>
        <translation>Geladene Datei: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="299"/>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Bildgrösse ändern:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="310"/>
        <source>Do not resize</source>
        <translation>Bildgrösse nicht ändern</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="315"/>
        <source>100x100 (avatar)</source>
        <translation>100x100 (Avatar)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="320"/>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (Thumbnail)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="325"/>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (für Websites und E-Mail)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="330"/>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (für Messageboards)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="335"/>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (12-Zoll Monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="340"/>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (15-Zoll Monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="345"/>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (19-Zoll Monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="350"/>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (21-Zoll Monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="423"/>
        <source>Comma separated list</source>
        <translation>Kommagetrennte Liste</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="640"/>
        <source>Upload in progress...</source>
        <translation>Lade hoch...</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="361"/>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Datenschutz:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="371"/>
        <source>Private</source>
        <translation>Privat</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="381"/>
        <source>Public</source>
        <translation>Öffentlich</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="394"/>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Tags:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="459"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentifizierung erfordert das Setzen von Privacy und Tags im Thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Log-in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="552"/>
        <source>Upload now</source>
        <translation>Jetzt hochladen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="647"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="685"/>
        <source>File upload progress:</source>
        <translation>Fortschritt :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="709"/>
        <source>Total upload progress:</source>
        <translation>Gesamter Fortschritt :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="146"/>
        <source>File(s) loaded: %1</source>
        <translation>Datei(en) geladen: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <source>login</source>
        <translation>Anmeldung</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>anonymous</source>
        <translation>anonym</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="30"/>
        <source>Log in to use this features</source>
        <translation>Anmelden um dieses Feature zu nutzen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="212"/>
        <source>Log in to use these features</source>
        <translation>Anmelden um diese Features zu nutzen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="229"/>
        <location filename="../ImageShackUploadWidget.cpp" line="272"/>
        <source>Processing file %1 of %2</source>
        <translation>Bearbeite Datei %1 von %2</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="359"/>
        <source>Connection refused</source>
        <translation>Verbindung verweigert</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="360"/>
        <source>Remote host closed</source>
        <translation>Gegenseite geschlossen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="361"/>
        <source>Host not found</source>
        <translation>Host nicht gefunden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="362"/>
        <source>Timeout</source>
        <translation>Timeout</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="363"/>
        <source>Operation canceled</source>
        <translation>Vorgang abgebrochen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="364"/>
        <source>SSL handshake failed</source>
        <translation>SSL handshake gescheitert</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="365"/>
        <source>Proxy connection refused</source>
        <translation>Proxy hat Verbindung verweigert</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="366"/>
        <source>Proxy connection closed</source>
        <translation>Proxy-Verbindung geschlossen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="367"/>
        <source>Proxy not found</source>
        <translation>Proxy nicht gefunden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="368"/>
        <source>Proxy timeout</source>
        <translation>Proxy timeout</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="369"/>
        <source>Proxy authentication required</source>
        <translation>Proxy benötigt Authentifizierung</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="370"/>
        <source>Content access denied</source>
        <translation>Zugriff verweigert</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="371"/>
        <source>Content operation not permitted</source>
        <translation>Unerlaubter Vorgang</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="372"/>
        <source>Content not found</source>
        <translation>Inhalte nicht gefunden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="373"/>
        <source>Authentication required</source>
        <translation>Authentifizierung notwendig</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="374"/>
        <source>Protocol unknown</source>
        <translation>Unbekanntes Protokoll</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="375"/>
        <source>Protocol invalid operation</source>
        <translation>Fehlerhaftes Protokoll</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="376"/>
        <source>Unknown network</source>
        <translation>Unbekanntes Netzwerk</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="377"/>
        <source>Unknown proxy</source>
        <translation>Unbekannter Proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="378"/>
        <source>Unknown content</source>
        <translation>Unbekannte Inhalte</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="379"/>
        <source>Protocol failure</source>
        <translation>Protokoll gescheitert</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="380"/>
        <source>Content resend</source>
        <translation>Inhalt erneut gesandt</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="381"/>
        <source>Temporary network failure</source>
        <translation>Temporärer Netzwerkfehler</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="382"/>
        <location filename="../ImageShackUploadWidget.cpp" line="386"/>
        <source>Unknown error</source>
        <translation>Unbekannter Fehler</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="383"/>
        <source>Failed to open the file</source>
        <translation>Datei konnte nicht geöffnet werden</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="384"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Maximale Dateigröße (5Mb) erreicht</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="391"/>
        <source>Upload Error:</source>
        <translation>Fehler beim Hochladen :</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <source>Open Configuration File</source>
        <translation>Konfigurationsdatei öffnen</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Configuration file(*.ini)</source>
        <translation>Konfigurationsdatei (*.ini)</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="82"/>
        <location filename="../IniManager.cpp" line="219"/>
        <location filename="../IniManager.cpp" line="230"/>
        <location filename="../IniManager.cpp" line="241"/>
        <location filename="../IniManager.cpp" line="252"/>
        <location filename="../IniManager.cpp" line="335"/>
        <source>Configuration file loaded</source>
        <translation>Konfigurationsdatei geladen</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="85"/>
        <source>Incorrect settings file</source>
        <translation>Falsche Konfigurationsdatei</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source>Configuration file</source>
        <translation>Konfigurationsdatei</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source> saved successfully</source>
        <translation> erfolgreich gespeichert</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Save Configuration File</source>
        <translation>Konfigurationsdatei speichern</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="274"/>
        <source>Not recent files</source>
        <translation>Keine Konfigurationsdateien vorhanden</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="223"/>
        <source>English</source>
        <translation>Englisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="224"/>
        <source>French</source>
        <translation>Französisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="225"/>
        <source>Spanish</source>
        <translation>Spanisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="226"/>
        <source>German</source>
        <translation>Deutsch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="227"/>
        <source>Dutch</source>
        <translation>Holländer</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="228"/>
        <source>Italian</source>
        <translation>Italienisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="229"/>
        <source>Czech</source>
        <translation>Tschechisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="230"/>
        <source>Hungarian</source>
        <translation>Ungarisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="231"/>
        <source>Croatian</source>
        <translation>Kroatisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="232"/>
        <source>Portuguese</source>
        <translation>Portugiesisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="233"/>
        <source>Chinese</source>
        <translation>Chinesisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="234"/>
        <source>Russian</source>
        <translation>Russisch</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="109"/>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="222"/>
        <source>Select a language</source>
        <translation>Wählen Sie eine Sprache</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="107"/>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="108"/>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../MainWindow.cpp" line="286"/>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>Letzte Konfiguration kann nicht geladen werden. Das Konfigurationslayout wird zurückgesetzt.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="384"/>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>Möchten Sie die momentane Konfiguration speichern, bevor Sie Thumbnail me verlassen?</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="388"/>
        <source>saved successfully</source>
        <translation>erfolgreich gespeichert</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="480"/>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>gibt keine Truetype Font in dieser Ordner.Bitte wählen Sie ein anderen Font Ornder im Einstellungen Menü.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="553"/>
        <source>Toolbar</source>
        <translation>Werkzeugleiste</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="555"/>
        <source>File</source>
        <translation>Datei</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="556"/>
        <source>Edition</source>
        <translation>Version</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="557"/>
        <source>View</source>
        <translation>Betrachten</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="558"/>
        <source>Predefined Configuration</source>
        <translation>Vordefinierte Konfiguration</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="559"/>
        <location filename="../MainWindow.cpp" line="576"/>
        <source>About</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="562"/>
        <source>Configuration</source>
        <translation>Konfiguration</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="563"/>
        <source>Open</source>
        <translation>Öffnen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="564"/>
        <source>Import a configuration file</source>
        <translation>Konfiguration laden</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="565"/>
        <source>Import a recent configuration file</source>
        <translation>Eine der letzten Konfigurationen laden</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="566"/>
        <source>Save my current configuration</source>
        <translation>Konfiguration speichern</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="567"/>
        <source>Save my current configuration as</source>
        <translation>Konfiguration speichern als</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="568"/>
        <source>Print</source>
        <translation>Drucken</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="569"/>
        <source>Exit</source>
        <translation>Beenden</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="570"/>
        <source>Settings</source>
        <translation>Einstellungen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="571"/>
        <source>Zoom in</source>
        <translation>Vergrössern</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="572"/>
        <source>Zoom out</source>
        <translation>Verkleinern</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="573"/>
        <source>Clear all</source>
        <translation>Alles löschen</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="574"/>
        <source>Fullscreen</source>
        <translation>Vollbild</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="575"/>
        <source>Help</source>
        <translation>Hilfe</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="577"/>
        <source>About QT</source>
        <translation>Über QT</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="578"/>
        <source>Donate</source>
        <translation>Spende</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="579"/>
        <source>Website</source>
        <translation>Website</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="307"/>
        <source>Network Connection</source>
        <translation>Netzwerkverbindung</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="308"/>
        <source>Direct connection</source>
        <translation>Direktverbindung</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="309"/>
        <source>Use proxy server</source>
        <translation>Proxy benutzen</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="310"/>
        <source>Hostname</source>
        <translation>Hostname</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="311"/>
        <source>Port</source>
        <translation>Port</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="312"/>
        <source>Type</source>
        <translation>Typ</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="313"/>
        <source>Authentication</source>
        <translation>Authentifizierung</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="314"/>
        <source>Username</source>
        <translation>Username</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="315"/>
        <source>Password</source>
        <translation>Passwort</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="316"/>
        <source>Proxy Settings</source>
        <translation>Proxyeinstellungen</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="324"/>
        <source>No Printer Detected</source>
        <translation>Kein Drucker entdeckt</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="403"/>
        <source>Open to my default picture viewer</source>
        <translation>Standardbildbetrachtungsprogramm starten</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="404"/>
        <source>Save As</source>
        <translation>Speichern als</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="405"/>
        <source>Copy to clipboard</source>
        <translation>In die Zwischenablage kopieren</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="261"/>
        <source>failed to open this file in your default image viewer.</source>
        <translation>Datei konnte nicht im Standardbildbetrachtungsprogramm geöffnet werden.</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="278"/>
        <source>Save File</source>
        <translation>Datei speichern</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="304"/>
        <source>Saving the file failed</source>
        <translation>Speichern der Datei gescheitert</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="101"/>
        <source>Progression:</source>
        <translation>Fortschritt :</translation>
    </message>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="80"/>
        <source>Processing file %1 of %2: %3</source>
        <translation>Bearbeite Datei %1 von %2: %3</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../main.cpp" line="92"/>
        <source>Initialisation</source>
        <translation>Inititalisierung</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="97"/>
        <source>Widgets initialisation</source>
        <translation>Widget-Initialisierung</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="102"/>
        <source>Preferences reading</source>
        <translation>Lade Einstellungen</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="107"/>
        <source>Starting...</source>
        <translation>Starte...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <location filename="../SettingsWidget.cpp" line="227"/>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>OpenGL Version 3.0 oder höher ist nicht auf Ihrem System gefunden. Es wird deaktiviert.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="233"/>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>OpenGL nicht gefunden. Es wird deaktiviert.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="340"/>
        <source>Settings</source>
        <translation>Einstellungen</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="341"/>
        <source>General</source>
        <translation>Allgemein</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="342"/>
        <source>Fonts</source>
        <translation>Fonts</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="343"/>
        <source>Languages</source>
        <translation>Sprachen</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="344"/>
        <source>Network</source>
        <translation>Netzwerk</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <location filename="../SuccessDialog.cpp" line="226"/>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Datei speichern als:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="228"/>
        <source>Upload to ImageShack</source>
        <translation>Auf ImageShack hochladen</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="232"/>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Datei(en) speichern als:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="234"/>
        <source>Upload these files to ImageShack</source>
        <translation>Diese Dateien auf ImageShack hochladen</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="215"/>
        <source>Open Folder</source>
        <translation>Verzeichnis öffnen</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="216"/>
        <source>Close</source>
        <translation>Schliessen</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="116"/>
        <location filename="../ThumbnailEngine.cpp" line="126"/>
        <location filename="../ThumbnailEngine.cpp" line="143"/>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Mtn binary nicht gefunden. Vorgang abgebrochen.</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="117"/>
        <location filename="../ThumbnailEngine.cpp" line="127"/>
        <location filename="../ThumbnailEngine.cpp" line="144"/>
        <source>No fonts defined</source>
        <translation>Keine Fonts definiert</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="118"/>
        <source>Output path does not exist</source>
        <translation>Das Ausgabeverzeichnis existiert nicht</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="119"/>
        <source>Select an output folder, please</source>
        <translation>Bitte wählen Sie ein Ausgabeverzeichnis</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="130"/>
        <source>No file(s) loaded</source>
        <translation>Keine Datei(en) geladen</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="145"/>
        <source>No file selected</source>
        <translation>Keine Datei gewählt</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <location filename="../ThumbnailListwidget.cpp" line="105"/>
        <source>You must select a file to remove it from the list</source>
        <translation>Eine Datei muss ausgewählt sein um sie zu entfernen</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <location filename="../VerboseWindow.cpp" line="41"/>
        <location filename="../VerboseWindow.cpp" line="142"/>
        <source>Copy to clipboard</source>
        <translation>In die Zwischenablage kopieren</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="141"/>
        <source>Logs</source>
        <translation>Logs</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="38"/>
        <location filename="../VerboseWindow.cpp" line="143"/>
        <source>Clear all</source>
        <translation>Alles löschen</translation>
    </message>
</context>
</TS>
