<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="cs_CZ">
<context>
    <name>About</name>
    <message>
        <source>About</source>
        <translation>O</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <source>Copy to clipboard</source>
        <translation>Zkopíruj do schránky</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <source>Gap</source>
        <translation>Mezera</translation>
    </message>
    <message>
        <source>Rows</source>
        <translation>Řádků</translation>
    </message>
    <message>
        <source>Width</source>
        <translation>Šířka</translation>
    </message>
    <message>
        <source>Edge detection</source>
        <translation>Detekce hrany</translation>
    </message>
    <message>
        <source>Output Format</source>
        <translation>Výstupní formát</translation>
    </message>
    <message>
        <source>Blank skip</source>
        <translation>Vyjmi prázdné</translation>
    </message>
    <message>
        <source>Configuration</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <source>Quality</source>
        <translation>Kvalita</translation>
    </message>
    <message>
        <source>Columns</source>
        <translation>Sloupců</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <source>Path Output</source>
        <translation>Výstupní adresář</translation>
    </message>
    <message>
        <source>Same folder output as source</source>
        <translation>Stejné složce jako zdroj výkonu</translation>
    </message>
    <message>
        <source>Media list is already empty</source>
        <translation>Seznam médií je prázdný</translation>
    </message>
    <message>
        <source>Input and Output</source>
        <translation>Vstup a výstup</translation>
    </message>
    <message>
        <source>Load</source>
        <translation>Načti soubory</translation>
    </message>
    <message>
        <source>Reset</source>
        <translation>Vymaž vše</translation>
    </message>
    <message>
        <source>Delete Selection</source>
        <translation>Smaž vybrané</translation>
    </message>
    <message>
        <source>Preview selection file</source>
        <translation>Náhled vybraného souboru</translation>
    </message>
    <message>
        <source>Start</source>
        <translation>Start Konverze</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <source>Timestamp</source>
        <translation>Časové razítko</translation>
    </message>
    <message>
        <source>Upper Right</source>
        <translation>Pravý horní roh</translation>
    </message>
    <message>
        <source>Lower Right</source>
        <translation>Pravý dolní roh</translation>
    </message>
    <message>
        <source>Styles</source>
        <translation>Styl</translation>
    </message>
    <message>
        <source>Generated by Thumbnail me</source>
        <translation>Generated by Thumbnail me</translation>
    </message>
    <message>
        <source>Building Font Cache...</source>
        <translation>Building Font Cache...</translation>
    </message>
    <message>
        <source>Background Color</source>
        <translation>Barva pozadí</translation>
    </message>
    <message>
        <source>Lower Left</source>
        <translation>Levý dolní roh</translation>
    </message>
    <message>
        <source>Upper Left</source>
        <translation>Levý horní roh</translation>
    </message>
    <message>
        <source>Shadow Color</source>
        <translation>Barva stínu</translation>
    </message>
    <message>
        <source>Info Text</source>
        <translation>Info Text</translation>
    </message>
    <message>
        <source>Additional Title</source>
        <translation>Další titul</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <source>To</source>
        <translation>Na</translation>
    </message>
    <message>
        <source>From</source>
        <translation>Z</translation>
    </message>
    <message>
        <source>TimeLine</source>
        <translation>Časová osa</translation>
    </message>
    <message>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>Časová osa (není k dispozici) | Formát není plně podporován</translation>
    </message>
    <message>
        <source>Total duration</source>
        <translation>Celková doba</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <source>No fonts defined</source>
        <translation>Není definovaný font</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <source>Add</source>
        <translation>Přidat</translation>
    </message>
    <message>
        <source>Remove</source>
        <translation>Odstraň</translation>
    </message>
    <message>
        <source>No fonts found in this folder</source>
        <translation>Ve složce není žádný font</translation>
    </message>
    <message>
        <source>Select a font folder</source>
        <translation>Vyber adresář s fonty</translation>
    </message>
    <message>
        <source>You must select a path to remove it from the list</source>
        <translation>Je třeba vybrat cestu k odstranění ze seznamu</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <source>General Settings</source>
        <translation>Hlavní nastavení</translation>
    </message>
    <message>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>Nepodařilo se načíst poslední nastavení při startu</translation>
    </message>
    <message>
        <source>Output suffix:</source>
        <translation>Přípona výstupu :</translation>
    </message>
    <message>
        <source>Activate openGL to preview thumbnails</source>
        <translation>Aktivuji openGL pro náhled miniatur</translation>
    </message>
    <message>
        <source>Animate pixmap while rendering</source>
        <translation>Animovaný pixmap při vykreslování</translation>
    </message>
    <message>
        <source>Background color of preview window</source>
        <translation>Barva pozadí okna náhledu</translation>
    </message>
    <message>
        <source>Never ask me to save my configuration on exit</source>
        <translation>Neptej se mě na uložení nastavení při ukončení</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <source>Help</source>
        <translation>Pomoc</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <source>Login</source>
        <translation>Přihlášovací jméno</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Storno</translation>
    </message>
    <message>
        <source>Logout</source>
        <translation>Odhlaš se</translation>
    </message>
    <message>
        <source>Login as</source>
        <translation>Přihlaš se jako</translation>
    </message>
    <message>
        <source>Password</source>
        <translation>Heslo</translation>
    </message>
    <message>
        <source>Authentication failed. Check your username and password.</source>
        <translation>Ověření se nezdařilo. Zkontrolujte, Vaše uživatelské jméno a heslo.</translation>
    </message>
    <message>
        <source>Autologin</source>
        <translation>Automatické přihlášení</translation>
    </message>
    <message>
        <source>Remember Password</source>
        <translation>Zapamatuj si heslo</translation>
    </message>
    <message>
        <source>Login in progress...</source>
        <translation>Přihlášení ...</translation>
    </message>
    <message>
        <source>Username/E-mail</source>
        <translation>Přihlašovací jméno/E-Mail</translation>
    </message>
    <message>
        <source>Connection refused</source>
        <translation>Spojení odmítnuto</translation>
    </message>
    <message>
        <source>Remote host closed</source>
        <translation>Vzdálený host uzavřen</translation>
    </message>
    <message>
        <source>Host not found</source>
        <translation>Host nebyl nalezen</translation>
    </message>
    <message>
        <source>Timeout</source>
        <translation>Časový limit</translation>
    </message>
    <message>
        <source>Operation canceled</source>
        <translation>Operace zrušena</translation>
    </message>
    <message>
        <source>SSL handshake failed</source>
        <translation>SSL spojení odmítnuto</translation>
    </message>
    <message>
        <source>Proxy connection refused</source>
        <translation>Proxy spojení odmítnuto</translation>
    </message>
    <message>
        <source>Proxy connection closed</source>
        <translation>Proxy spojení ukončeno</translation>
    </message>
    <message>
        <source>Proxy not found</source>
        <translation>Proxy není nalezena</translation>
    </message>
    <message>
        <source>Proxy timeout</source>
        <translation>Časový limit proxy vypršel</translation>
    </message>
    <message>
        <source>Proxy authentication required</source>
        <translation>Proxy autentifikace je požadována</translation>
    </message>
    <message>
        <source>Content access denied</source>
        <translation>Požadovaný přístup odepřen</translation>
    </message>
    <message>
        <source>Content operation not permitted</source>
        <translation>Požadovaná operace není povolena</translation>
    </message>
    <message>
        <source>Content not found</source>
        <translation>Požadováno není</translation>
    </message>
    <message>
        <source>Authentication required</source>
        <translation>Přihlášení je požadováno</translation>
    </message>
    <message>
        <source>Protocol unknown</source>
        <translation>Protokol není</translation>
    </message>
    <message>
        <source>Protocol invalid operation</source>
        <translation>Protokol špatných operací</translation>
    </message>
    <message>
        <source>Unknown network</source>
        <translation>Neznámá síť</translation>
    </message>
    <message>
        <source>Unknown proxy</source>
        <translation>Neznámá proxy</translation>
    </message>
    <message>
        <source>Unknown content</source>
        <translation>Neznámý požadavek</translation>
    </message>
    <message>
        <source>Protocol failure</source>
        <translation>Protokolování selhalo</translation>
    </message>
    <message>
        <source>Content resend</source>
        <translation>Požadováno odeslání</translation>
    </message>
    <message>
        <source>Temporary network failure</source>
        <translation>Dočasný výpadek sítě</translation>
    </message>
    <message>
        <source>Unknown error</source>
        <translation>Neznámá chyba</translation>
    </message>
    <message>
        <source>Failed to open the file</source>
        <translation>Nepodařilo se otevřít soubor</translation>
    </message>
    <message>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Maximální velikost (5 MB)</translation>
    </message>
    <message>
        <source>Upload Error:</source>
        <translation>Chyba nahrávání :</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <source>Close</source>
        <translation>Zavři</translation>
    </message>
    <message>
        <source>Uploaded files</source>
        <translation>Nahrané soubory</translation>
    </message>
    <message>
        <source>File 1 of 1</source>
        <translation>Soubor 1 z 1</translation>
    </message>
    <message>
        <source>Thumbnail for forums 1</source>
        <translation>Náhled na fórum 1</translation>
    </message>
    <message>
        <source>Thumbnail for forums 2</source>
        <translation>Náhled na fórum 2</translation>
    </message>
    <message>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink na fórum 1</translation>
    </message>
    <message>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink na fórum 2</translation>
    </message>
    <message>
        <source>Thumbnail for web</source>
        <translation>Náhled na web</translation>
    </message>
    <message>
        <source>Hotlink for web</source>
        <translation>Hotlink na web</translation>
    </message>
    <message>
        <source>Short link</source>
        <translation>Krátký link</translation>
    </message>
    <message>
        <source>Direct link</source>
        <translation>Přímý odkaz</translation>
    </message>
    <message>
        <source>File %1 of %2</source>
        <translation>Soubor %1 z %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <source>Processing file %1 of %2</source>
        <translation>Zpracování souboru %1 z %2</translation>
    </message>
    <message>
        <source>login</source>
        <translation>přihlásit</translation>
    </message>
    <message>
        <source>Proxy not found</source>
        <translation>Proxy není nalezena</translation>
    </message>
    <message>
        <source>Host not found</source>
        <translation>Host nebyl nalezen</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Nahrej: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;Bez přihlášení&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (pro webové stránky a e-mail)</translation>
    </message>
    <message>
        <source>Protocol unknown</source>
        <translation>Protokol není</translation>
    </message>
    <message>
        <source>Comma separated list</source>
        <translation>Oddělit čárkami</translation>
    </message>
    <message>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Změna velikosti odrázku:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Content resend</source>
        <translation>Požadováno odeslání</translation>
    </message>
    <message>
        <source>Proxy connection refused</source>
        <translation>Proxy spojení odmítnuto</translation>
    </message>
    <message>
        <source>File upload progress:</source>
        <translation>Postup nahrávání souborů :</translation>
    </message>
    <message>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (12-palcový monitor)</translation>
    </message>
    <message>
        <source>Failed to open the file</source>
        <translation>Nepodařilo se otevřít soubor</translation>
    </message>
    <message>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (19-palcový monitor)</translation>
    </message>
    <message>
        <source>100x100 (avatar)</source>
        <translation>100x100 (avatar)</translation>
    </message>
    <message>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Maximální velikost (5 MB)</translation>
    </message>
    <message>
        <source>Upload mode:</source>
        <translation>Nahrávaní :</translation>
    </message>
    <message>
        <source>Remote host closed</source>
        <translation>Vzdálený host uzavřen</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Storno</translation>
    </message>
    <message>
        <source>Content access denied</source>
        <translation>Požadovaný přístup odepřen</translation>
    </message>
    <message>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (náhled)</translation>
    </message>
    <message>
        <source>Upload now</source>
        <translation>Nahrej nyní</translation>
    </message>
    <message>
        <source>Public</source>
        <translation>Veřejné</translation>
    </message>
    <message>
        <source>Log in to use these features</source>
        <translation>Je nutno se přihlásit pro použití těchto funkcí</translation>
    </message>
    <message>
        <source>Temporary network failure</source>
        <translation>Dočasný výpadek sítě</translation>
    </message>
    <message>
        <source>Proxy connection closed</source>
        <translation>Proxy spojení ukončeno</translation>
    </message>
    <message>
        <source>anonymous</source>
        <translation>bez přihlášení</translation>
    </message>
    <message>
        <source>Unknown network</source>
        <translation>Neznámá síť</translation>
    </message>
    <message>
        <source>Connection refused</source>
        <translation>Spojení odmítnuto</translation>
    </message>
    <message>
        <source>Protocol failure</source>
        <translation>Protokolování selhalo</translation>
    </message>
    <message>
        <source>Proxy authentication required</source>
        <translation>Proxy autentifikace je požadována</translation>
    </message>
    <message>
        <source>Total upload progress:</source>
        <translation>Celkový postup nahrávání :</translation>
    </message>
    <message>
        <source>Private</source>
        <translation>Soukromé</translation>
    </message>
    <message>
        <source>Upload Error:</source>
        <translation>Chyba nahrávání :</translation>
    </message>
    <message>
        <source>File loaded: %1</source>
        <translation>Soubor nahrán: %1</translation>
    </message>
    <message>
        <source>Log in to use this features</source>
        <translation>Je nutno se přihlásit pro použití této funkce</translation>
    </message>
    <message>
        <source>Protocol invalid operation</source>
        <translation>Protokol špatných operací</translation>
    </message>
    <message>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (15-palcový monitor)</translation>
    </message>
    <message>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Soukromé:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Operation canceled</source>
        <translation>Operace zrušena</translation>
    </message>
    <message>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Značky:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Content not found</source>
        <translation>Požadováno není</translation>
    </message>
    <message>
        <source>Authentication required</source>
        <translation>Přihlášení je požadováno</translation>
    </message>
    <message>
        <source>SSL handshake failed</source>
        <translation>SSL spojení odmítnuto</translation>
    </message>
    <message>
        <source>Content operation not permitted</source>
        <translation>Požadovaná operace není povolena</translation>
    </message>
    <message>
        <source>Timeout</source>
        <translation>Časový limit</translation>
    </message>
    <message>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (pro nástěnku)</translation>
    </message>
    <message>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (21-palcový monitor)</translation>
    </message>
    <message>
        <source>File(s) loaded: %1</source>
        <translation>Soubor(y) nahrán(y): %1</translation>
    </message>
    <message>
        <source>Upload in progress...</source>
        <translation>Nahrává se ...</translation>
    </message>
    <message>
        <source>Unknown content</source>
        <translation>Neznámý požadavek</translation>
    </message>
    <message>
        <source>Unknown proxy</source>
        <translation>Neznámá proxy</translation>
    </message>
    <message>
        <source>Unknown error</source>
        <translation>Neznámá chyba</translation>
    </message>
    <message>
        <source>Do not resize</source>
        <translation>Bez změny velikosti</translation>
    </message>
    <message>
        <source>Proxy timeout</source>
        <translation>Časový limit proxy vypršel</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Vyžaduje se přihlášení k nastavení soukromí a značek náhledů&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Přihlaš se&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <source>Save Configuration File</source>
        <translation>Ulož soubor s nastavením</translation>
    </message>
    <message>
        <source>Open Configuration File</source>
        <translation>Otevři soubor s nastavením</translation>
    </message>
    <message>
        <source>Configuration file</source>
        <translation>Soubor s nastavením</translation>
    </message>
    <message>
        <source>Configuration file loaded</source>
        <translation>Soubor s nastavením byl načten</translation>
    </message>
    <message>
        <source>Not recent files</source>
        <translation>Nejsou poslední soubory</translation>
    </message>
    <message>
        <source> saved successfully</source>
        <translation>uložení bylo úspěšné</translation>
    </message>
    <message>
        <source>Configuration file(*.ini)</source>
        <translation>Soubor s nastavením(*.ini)</translation>
    </message>
    <message>
        <source>Incorrect settings file</source>
        <translation>Nesprávný soubor s nastavením</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <source>French</source>
        <translation>Francouzsky</translation>
    </message>
    <message>
        <source>German</source>
        <translation>Německy</translation>
    </message>
    <message>
        <source>Spanish</source>
        <translation>Španělsky</translation>
    </message>
    <message>
        <source>English</source>
        <translation>Anglicky</translation>
    </message>
    <message>
        <source>Select a language</source>
        <translation>Vyber jazyk</translation>
    </message>
    <message>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <source>Dutch</source>
        <translation>Holandsky</translation>
    </message>
    <message>
        <source>Italian</source>
        <translation>Italsky</translation>
    </message>
    <message>
        <source>Czech</source>
        <translation>Česky</translation>
    </message>
    <message>
        <source>Hungarian</source>
        <translation>Maďarsky</translation>
    </message>
    <message>
        <source>Croatian</source>
        <translation>Chorvatsky</translation>
    </message>
    <message>
        <source>Portuguese</source>
        <translation>Portugalsky</translation>
    </message>
    <message>
        <source>Chinese</source>
        <translation>Číňan</translation>
    </message>
    <message>
        <source>Russian</source>
        <translation>Rus</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>Poslední soubor s nastavením nelze otevřít. Nastavení se zresetuje.</translation>
    </message>
    <message>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>Chceš uložit aktuální konfiguraci před ukončením Thumbnail me?</translation>
    </message>
    <message>
        <source>saved successfully</source>
        <translation>úspěšně uloženo</translation>
    </message>
    <message>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>obsahuje neznámý soubor s truetype fontem. Prosím vyber sjinou složku v Nastavení.</translation>
    </message>
    <message>
        <source>Toolbar</source>
        <translation>Panel nástrojů</translation>
    </message>
    <message>
        <source>File</source>
        <translation>Soubor</translation>
    </message>
    <message>
        <source>Edition</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <source>View</source>
        <translation>Náhled</translation>
    </message>
    <message>
        <source>Predefined Configuration</source>
        <translation>Předdefinované nastavení</translation>
    </message>
    <message>
        <source>About</source>
        <translation>O</translation>
    </message>
    <message>
        <source>Configuration</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <source>Open</source>
        <translation>Otevři</translation>
    </message>
    <message>
        <source>Import a configuration file</source>
        <translation>Import souboru s nastavením</translation>
    </message>
    <message>
        <source>Import a recent configuration file</source>
        <translation>Import posledního souboru s nastavením</translation>
    </message>
    <message>
        <source>Save my current configuration</source>
        <translation>Ulož současné nastavení</translation>
    </message>
    <message>
        <source>Save my current configuration as</source>
        <translation>Ulož současné nastavení jako</translation>
    </message>
    <message>
        <source>Print</source>
        <translation>Tisk</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation>Konec</translation>
    </message>
    <message>
        <source>Settings</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <source>Zoom in</source>
        <translation>Zvětšit</translation>
    </message>
    <message>
        <source>Zoom out</source>
        <translation>Zmenšit</translation>
    </message>
    <message>
        <source>Clear all</source>
        <translation>Smaž vše</translation>
    </message>
    <message>
        <source>Fullscreen</source>
        <translation>Celá obrazovka</translation>
    </message>
    <message>
        <source>Help</source>
        <translation>Pomoc</translation>
    </message>
    <message>
        <source>About QT</source>
        <translation>O QT</translation>
    </message>
    <message>
        <source>Donate</source>
        <translation>Daruj</translation>
    </message>
    <message>
        <source>Website</source>
        <translation>Internetové stránky</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <source>Port</source>
        <translation>Port</translation>
    </message>
    <message>
        <source>Type</source>
        <translation>Typ</translation>
    </message>
    <message>
        <source>Use proxy server</source>
        <translation>Použij proxy server</translation>
    </message>
    <message>
        <source>Authentication</source>
        <translation>Ověření</translation>
    </message>
    <message>
        <source>Proxy Settings</source>
        <translation>Nastavení proxy</translation>
    </message>
    <message>
        <source>Hostname</source>
        <translation>Hostname</translation>
    </message>
    <message>
        <source>Password</source>
        <translation>Heslo</translation>
    </message>
    <message>
        <source>Network Connection</source>
        <translation>Síťové připojení</translation>
    </message>
    <message>
        <source>Username</source>
        <translation>Jméno</translation>
    </message>
    <message>
        <source>Direct connection</source>
        <translation>Přímé spojení</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <source>Saving the file failed</source>
        <translation>Uložení se nezdařilo</translation>
    </message>
    <message>
        <source>Copy to clipboard</source>
        <translation>Kopíruj do schránky</translation>
    </message>
    <message>
        <source>Open to my default picture viewer</source>
        <translation>Otevři výchozí prohlížeč obrázků</translation>
    </message>
    <message>
        <source>Save As</source>
        <translation>Ulož jako</translation>
    </message>
    <message>
        <source>failed to open this file in your default image viewer.</source>
        <translation>Nepodařilo se otevřít tento soubor v výchozím prohlížeči obrázků.</translation>
    </message>
    <message>
        <source>Save File</source>
        <translation>Ulož</translation>
    </message>
    <message>
        <source>No Printer Detected</source>
        <translation type="unfinished">Tiskárna nenalezena</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <source>Processing file %1 of %2: %3</source>
        <translation>Zpracování souboru %1 ze %2: %3</translation>
    </message>
    <message>
        <source>Progression:</source>
        <translation>Zpracování :</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Preferences reading</source>
        <translation>Předvolby čtení</translation>
    </message>
    <message>
        <source>Initialisation</source>
        <translation>Inicializace</translation>
    </message>
    <message>
        <source>Widgets initialisation</source>
        <translation>Widgety inicializace</translation>
    </message>
    <message>
        <source>Starting...</source>
        <translation>Zahájení ...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <source>Fonts</source>
        <translation>Fonty</translation>
    </message>
    <message>
        <source>Network</source>
        <translation>Síť</translation>
    </message>
    <message>
        <source>Languages</source>
        <translation>Jazyky</translation>
    </message>
    <message>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>OpenGL verze 3.0 nebo vyšší, není ve vašem systému. Bude vypnut.</translation>
    </message>
    <message>
        <source>Settings</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <source>General</source>
        <translation>Hlavní</translation>
    </message>
    <message>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>OpenGL nebyl detekován na vašem systému. Bude vypnut.</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <source>Close</source>
        <translation>Zavři</translation>
    </message>
    <message>
        <source>Upload these files to ImageShack</source>
        <translation>Nahrajte tyto soubory na ImageShack</translation>
    </message>
    <message>
        <source>Upload to ImageShack</source>
        <translation>Nahrát na ImageShack</translation>
    </message>
    <message>
        <source>Open Folder</source>
        <translation>Otevři adresář</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Soubor uložen jako:&lt;/h1&gt;</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Soubor(y) uloženy jako:&lt;/h1&gt;</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <source>Select an output folder, please</source>
        <translation>Vyberte výstupní adresář, prosím</translation>
    </message>
    <message>
        <source>No file selected</source>
        <translation>Není vybrán žádný soubor</translation>
    </message>
    <message>
        <source>No file(s) loaded</source>
        <translation>Nenahrán(y) žádný soubor(y)</translation>
    </message>
    <message>
        <source>No fonts defined</source>
        <translation>Není definován font</translation>
    </message>
    <message>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Mtn binary nebyl nalezen. Operace zrušena.</translation>
    </message>
    <message>
        <source>Output path does not exist</source>
        <translation>Výstupní adresář neexistuje</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <source>You must select a file to remove it from the list</source>
        <translation>Musíte vybrat soubor, který chcete odstranit ze seznamu</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <source>Logs</source>
        <translation>Log</translation>
    </message>
    <message>
        <source>Clear all</source>
        <translation>Vymaž vše</translation>
    </message>
    <message>
        <source>Copy to clipboard</source>
        <translation>Kopíruj do schránky</translation>
    </message>
</context>
</TS>
