<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="hr_HR" sourcelanguage="en_US">
<context>
    <name>About</name>
    <message>
        <location filename="../About.cpp" line="119"/>
        <source>About</source>
        <translation>O</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <location filename="../copyablelineedit.ui" line="84"/>
        <source>Copy to clipboard</source>
        <translation>Kopiraj u međuspremnik</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <location filename="../DockConf.cpp" line="361"/>
        <location filename="../DockConf.cpp" line="362"/>
        <source>Configuration</source>
        <translation>Konfiguracija</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="363"/>
        <source>Output Format</source>
        <translation>Izlazni format</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="364"/>
        <source>Columns</source>
        <translation>Stupci</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="365"/>
        <source>Rows</source>
        <translation>Redci</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="366"/>
        <source>Width</source>
        <translation>Širina</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="367"/>
        <source>Gap</source>
        <translation>Zazor</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="368"/>
        <source>Quality</source>
        <translation>Kvaliteta</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="369"/>
        <source>Blank skip</source>
        <translation>Preskoči prazno</translation>
    </message>
    <message>
        <location filename="../DockConf.cpp" line="370"/>
        <source>Edge detection</source>
        <translation>Otkrivanje ruba</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <location filename="../DockInputOutput.cpp" line="55"/>
        <location filename="../DockInputOutput.cpp" line="432"/>
        <source>Path Output</source>
        <translation>Odredišna mapa</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="70"/>
        <location filename="../DockInputOutput.cpp" line="434"/>
        <source>Same folder output as source</source>
        <translation>Koristi izvornu mapu kao odredište</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="374"/>
        <source>Media list is already empty</source>
        <translation>Popis medija je prazan</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="427"/>
        <source>Input and Output</source>
        <translation>Ulaz i Izlaz</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="428"/>
        <source>Load</source>
        <translation>Učitavanje</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="429"/>
        <source>Reset</source>
        <translation>Vraćanje na polazne postavke</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="430"/>
        <source>Start</source>
        <translation>Početak pretvorbe</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="431"/>
        <source>Delete Selection</source>
        <translation>Obriši odabrano</translation>
    </message>
    <message>
        <location filename="../DockInputOutput.cpp" line="433"/>
        <source>Preview selection file</source>
        <translation>Pregled odabrane datoteke</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <location filename="../DockStyles.cpp" line="527"/>
        <location filename="../DockStyles.cpp" line="528"/>
        <source>Styles</source>
        <translation>Stilovi</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="529"/>
        <source>Generated by Thumbnail me</source>
        <translation>Napravljeno pomoću Thumbnail me</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="530"/>
        <source>Info Text</source>
        <translation>Info tekst</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="531"/>
        <source>Timestamp</source>
        <translation>Vremenska oznaka</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="535"/>
        <location filename="../DockStyles.cpp" line="536"/>
        <source>Building Font Cache...</source>
        <translation>Keširanje Fonta...</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Left</source>
        <translation>Dolje lijevo</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Lower Right</source>
        <translation>Dolje desno</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Right</source>
        <translation>Gore desno</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="539"/>
        <source>Upper Left</source>
        <translation>Gore lijevo</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="532"/>
        <source>Additional Title</source>
        <translation>Dodatni natpis</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="533"/>
        <source>Background Color</source>
        <translation>Boja pozadine</translation>
    </message>
    <message>
        <location filename="../DockStyles.cpp" line="534"/>
        <source>Shadow Color</source>
        <translation>Boja sjene</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <location filename="../DockTimeLine.cpp" line="185"/>
        <location filename="../DockTimeLine.cpp" line="192"/>
        <location filename="../DockTimeLine.cpp" line="206"/>
        <source>TimeLine</source>
        <translation>Vremenski slijed</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="142"/>
        <location filename="../DockTimeLine.cpp" line="186"/>
        <location filename="../DockTimeLine.cpp" line="193"/>
        <location filename="../DockTimeLine.cpp" line="200"/>
        <location filename="../DockTimeLine.cpp" line="207"/>
        <source>From</source>
        <translation>Od</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="153"/>
        <location filename="../DockTimeLine.cpp" line="187"/>
        <location filename="../DockTimeLine.cpp" line="194"/>
        <location filename="../DockTimeLine.cpp" line="201"/>
        <location filename="../DockTimeLine.cpp" line="208"/>
        <source>To</source>
        <translation>Do</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="188"/>
        <location filename="../DockTimeLine.cpp" line="195"/>
        <location filename="../DockTimeLine.cpp" line="202"/>
        <location filename="../DockTimeLine.cpp" line="209"/>
        <source>Total duration</source>
        <translation>Ukupno trajanje</translation>
    </message>
    <message>
        <location filename="../DockTimeLine.cpp" line="131"/>
        <location filename="../DockTimeLine.cpp" line="199"/>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>Vremenski slijed (Nedostupno) | Medij nije u potpunosti podržan</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <location filename="../FontMapComboBox.cpp" line="132"/>
        <source>No fonts defined</source>
        <translation>Nema definiranih fontova</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="197"/>
        <source>Add</source>
        <translation>Dodaj</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="198"/>
        <source>Remove</source>
        <translation>Ukloni</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="87"/>
        <source>No fonts found in this folder</source>
        <translation>U ovoj mapi nema fontova</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="81"/>
        <source>Select a font folder</source>
        <translation>Izaberite mapu s fontovima</translation>
    </message>
    <message>
        <location filename="../FontsSettingsTab.cpp" line="96"/>
        <source>You must select a path to remove it from the list</source>
        <translation>Za uklanjanje s popisa morate odabrati putanju</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="239"/>
        <source>Never ask me to save my configuration on exit</source>
        <translation>Prilikom izlaska nikad ne pitaj za spremanje moje konfiguracije</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="240"/>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>Prilikom pokretanja ne učitavaj zadnju konfiguraciju</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="241"/>
        <source>Background color of preview window</source>
        <translation>Boja pozadine prozora pregleda</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="242"/>
        <source>Output suffix:</source>
        <translation>Izlaz sufiks :</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="49"/>
        <location filename="../GeneralSettingsTab.cpp" line="243"/>
        <source>Activate openGL to preview thumbnails</source>
        <translation>Aktivirajte OpenGL za pregled sličica</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="52"/>
        <location filename="../GeneralSettingsTab.cpp" line="244"/>
        <source>Animate pixmap while rendering</source>
        <translation>Animiraj pixmap tijekom renderiranja</translation>
    </message>
    <message>
        <location filename="../GeneralSettingsTab.cpp" line="238"/>
        <source>General Settings</source>
        <translation>Opće Postavke</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <location filename="../HelpWidget.cpp" line="110"/>
        <source>Help</source>
        <translation>Pomoć</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="426"/>
        <source>Password</source>
        <translation>Zaporka</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="427"/>
        <source>Remember Password</source>
        <translation>Zapamti zaporku</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="55"/>
        <location filename="../ImageShackLoginWidget.cpp" line="429"/>
        <source>Login</source>
        <translation>Prijava</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="87"/>
        <location filename="../ImageShackLoginWidget.cpp" line="430"/>
        <source>Login in progress...</source>
        <translation>Prijava u tijeku...</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="89"/>
        <location filename="../ImageShackLoginWidget.cpp" line="432"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="102"/>
        <location filename="../ImageShackLoginWidget.cpp" line="431"/>
        <source>Logout</source>
        <translation>Odjava</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="225"/>
        <source>Authentication failed. Check your username and password.</source>
        <translation>Provjera autentičnosti nije uspjela. Provjerite svoje korisničko ime i lozinku.</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="239"/>
        <source>Connection refused</source>
        <translation>Konekcija refused</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="240"/>
        <source>Remote host closed</source>
        <translation>Udaljeni domaćin zatvoren</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="241"/>
        <source>Host not found</source>
        <translation>Domaćin nije pronađen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="242"/>
        <source>Timeout</source>
        <translation>Vrijeme isteklo</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="243"/>
        <source>Operation canceled</source>
        <translation>Operacija otkazana</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="244"/>
        <source>SSL handshake failed</source>
        <translation>SSL handshake pogreška</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="245"/>
        <source>Proxy connection refused</source>
        <translation>Proxy veza odbijena</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="246"/>
        <source>Proxy connection closed</source>
        <translation>Proxy konekcija zatvorena</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="247"/>
        <source>Proxy not found</source>
        <translation>Proxy nije pronađen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="248"/>
        <source>Proxy timeout</source>
        <translation>Proxy isteklo vrijeme</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="249"/>
        <source>Proxy authentication required</source>
        <translation>Proxy zahtijeva autentifikaciju</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="250"/>
        <source>Content access denied</source>
        <translation>Zahtijev za vezu odbijen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="251"/>
        <source>Content operation not permitted</source>
        <translation>Sadržaj operacija nije odobrena</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="252"/>
        <source>Content not found</source>
        <translation>Sadržaj nije pronađen</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="253"/>
        <source>Authentication required</source>
        <translation>Potrebna provjera identiteta</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="254"/>
        <source>Protocol unknown</source>
        <translation>Protokol nepoznat</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="255"/>
        <source>Protocol invalid operation</source>
        <translation>Protokol nevažeći rad</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="256"/>
        <source>Unknown network</source>
        <translation>Nepoznata mreža</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="257"/>
        <source>Unknown proxy</source>
        <translation>Nepoznat proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="258"/>
        <source>Unknown content</source>
        <translation>Nepoznat sadržaj</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="259"/>
        <source>Protocol failure</source>
        <translation>Krivi protokol</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="260"/>
        <source>Content resend</source>
        <translation>Ponovno slanje sadržaja</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="261"/>
        <source>Temporary network failure</source>
        <translation>Privremena mrežna pogreška</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="262"/>
        <location filename="../ImageShackLoginWidget.cpp" line="266"/>
        <source>Unknown error</source>
        <translation>Nepoznata pogreška</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="263"/>
        <source>Failed to open the file</source>
        <translation>Neuspješno otvaranje datoteke</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="264"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Dosegnuta maksimalna veličina (5 Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="270"/>
        <source>Upload Error:</source>
        <translation>Upload greška :</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="297"/>
        <source>Login as</source>
        <translation>Prijavi se kao</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="425"/>
        <source>Username/E-mail</source>
        <translation>Korisničko ime/E-mail</translation>
    </message>
    <message>
        <location filename="../ImageShackLoginWidget.cpp" line="428"/>
        <source>Autologin</source>
        <translation>Automatska prijava</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="20"/>
        <source>Uploaded files</source>
        <translation>Poslano datoteka</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="109"/>
        <source>File 1 of 1</source>
        <translation>Datoteka 1 od 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.ui" line="334"/>
        <source>Close</source>
        <translation>Zatvori</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="178"/>
        <source>Direct link</source>
        <translation>Izravna veza</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="179"/>
        <source>Short link</source>
        <translation>Kratki link</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="180"/>
        <source>Hotlink for web</source>
        <translation>Hiperveza za web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="181"/>
        <source>Thumbnail for web</source>
        <translation>Minijatura za web</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="182"/>
        <source>Thumbnail for forums 1</source>
        <translation>Minijatura za forume 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="183"/>
        <source>Thumbnail for forums 2</source>
        <translation>Minijatura za forume 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="184"/>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink za forume 1</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="185"/>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink za forume 2</translation>
    </message>
    <message>
        <location filename="../ImageShackResultWidget.cpp" line="100"/>
        <source>File %1 of %2</source>
        <translation>Datoteka %1 od %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="30"/>
        <source>Log in to use this features</source>
        <translation>Prijavite se kako bi koristili ove značajke</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="136"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload način: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonimni&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="215"/>
        <location filename="../ImageShackUploadWidget.cpp" line="247"/>
        <source>File loaded: %1</source>
        <translation>Datoteka učitavanje: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="299"/>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Promjena veličine slike:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="310"/>
        <source>Do not resize</source>
        <translation>Ne mijenjaj veličinu</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="315"/>
        <source>100x100 (avatar)</source>
        <translation>100x100 (avatar)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="320"/>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (minijatura)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="325"/>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (za web stranice i email)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="330"/>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (za oglasne ploče)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="335"/>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (12-inčni monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="340"/>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (15-inčni monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="345"/>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (19-inčni monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="350"/>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (21-inčni monitor)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="361"/>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Privatnost:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="371"/>
        <source>Private</source>
        <translation>Privatno</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="381"/>
        <source>Public</source>
        <translation>Javno</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="394"/>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Tagovi:&lt;/b&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="423"/>
        <source>Comma separated list</source>
        <translation>Zarezom odvojen popis</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="459"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Provjera identiteta neophodna za podešavanje Privatnosti i oznaka na sličice&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="552"/>
        <source>Upload now</source>
        <translation>Pošalji odmah</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="640"/>
        <source>Upload in progress...</source>
        <translation>Slanje u tijeku...</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="647"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="685"/>
        <source>File upload progress:</source>
        <translation>Napredak slanja datoteke :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.ui" line="709"/>
        <source>Total upload progress:</source>
        <translation>Dosada poslano ukupno :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="146"/>
        <source>File(s) loaded: %1</source>
        <translation>Datoteka(e) učitano: %1</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>Upload mode:</source>
        <translation>Upload način :</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="203"/>
        <source>login</source>
        <translation>prijava</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="210"/>
        <source>anonymous</source>
        <translation>anonimni</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="212"/>
        <source>Log in to use these features</source>
        <translation>Prijavite se kako bi koristili te značajke</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="229"/>
        <location filename="../ImageShackUploadWidget.cpp" line="272"/>
        <source>Processing file %1 of %2</source>
        <translation>Obrada datoteka %1 od %2</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="359"/>
        <source>Connection refused</source>
        <translation>Konekcija refused</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="360"/>
        <source>Remote host closed</source>
        <translation>Udaljeni domaćin zatvoren</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="361"/>
        <source>Host not found</source>
        <translation>Domaćin nije pronađen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="362"/>
        <source>Timeout</source>
        <translation>Vrijeme isteklo</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="363"/>
        <source>Operation canceled</source>
        <translation>Operacija otkazana</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="364"/>
        <source>SSL handshake failed</source>
        <translation>SSL handshake pogreška</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="365"/>
        <source>Proxy connection refused</source>
        <translation>Proxy veza odbijena</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="366"/>
        <source>Proxy connection closed</source>
        <translation>Proxy konekcija zatvorena</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="367"/>
        <source>Proxy not found</source>
        <translation>Proxy nije pronađen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="368"/>
        <source>Proxy timeout</source>
        <translation>Proxy isteklo vrijeme</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="369"/>
        <source>Proxy authentication required</source>
        <translation>Proxy zahtijeva autentifikaciju</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="370"/>
        <source>Content access denied</source>
        <translation>Zahtijev za vezu odbijen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="371"/>
        <source>Content operation not permitted</source>
        <translation>Sadržaj operacija nije odobrena</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="372"/>
        <source>Content not found</source>
        <translation>Sadržaj nije pronađen</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="373"/>
        <source>Authentication required</source>
        <translation>Potrebna provjera identiteta</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="374"/>
        <source>Protocol unknown</source>
        <translation>Protokol nepoznat</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="375"/>
        <source>Protocol invalid operation</source>
        <translation>Protokol nevažeći rad</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="376"/>
        <source>Unknown network</source>
        <translation>Nepoznata mreža</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="377"/>
        <source>Unknown proxy</source>
        <translation>Nepoznat proxy</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="378"/>
        <source>Unknown content</source>
        <translation>Nepoznat sadržaj</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="379"/>
        <source>Protocol failure</source>
        <translation>Krivi protokol</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="380"/>
        <source>Content resend</source>
        <translation>Ponovno slanje sadržaja</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="381"/>
        <source>Temporary network failure</source>
        <translation>Privremena mrežna pogreška</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="382"/>
        <location filename="../ImageShackUploadWidget.cpp" line="386"/>
        <source>Unknown error</source>
        <translation>Nepoznata pogreška</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="383"/>
        <source>Failed to open the file</source>
        <translation>Neuspješno otvaranje datoteke</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="384"/>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Dosegnuta maksimalna veličina (5 Mb)</translation>
    </message>
    <message>
        <location filename="../ImageShackUploadWidget.cpp" line="391"/>
        <source>Upload Error:</source>
        <translation>Upload greška :</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <source>Open Configuration File</source>
        <translation>Otvori konfiguracijsku datoteku</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="51"/>
        <location filename="../IniManager.cpp" line="53"/>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Configuration file(*.ini)</source>
        <translation>Konfiguracijska datoteka(*.ini)</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="82"/>
        <location filename="../IniManager.cpp" line="219"/>
        <location filename="../IniManager.cpp" line="230"/>
        <location filename="../IniManager.cpp" line="241"/>
        <location filename="../IniManager.cpp" line="252"/>
        <location filename="../IniManager.cpp" line="335"/>
        <source>Configuration file loaded</source>
        <translation>Konfiguracijska datoteka učitana</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="85"/>
        <source>Incorrect settings file</source>
        <translation>Neispravna datoteka postavki</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source>Configuration file</source>
        <translation>Konfiguracijska datoteka</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="187"/>
        <source> saved successfully</source>
        <translation>spremanje uspješno završeno</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="199"/>
        <location filename="../IniManager.cpp" line="201"/>
        <source>Save Configuration File</source>
        <translation>Spremi konfiguracijsku datoteku</translation>
    </message>
    <message>
        <location filename="../IniManager.cpp" line="274"/>
        <source>Not recent files</source>
        <translation>Nije nedavna datoteka</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="223"/>
        <source>English</source>
        <translation>Engleski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="224"/>
        <source>French</source>
        <translation>Francuski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="225"/>
        <source>Spanish</source>
        <translation>Španjolski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="226"/>
        <source>German</source>
        <translation>Njemački</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="227"/>
        <source>Dutch</source>
        <translation>Nizozemski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="228"/>
        <source>Italian</source>
        <translation>Italijanski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="229"/>
        <source>Czech</source>
        <translation>Češki</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="230"/>
        <source>Hungarian</source>
        <translation>Mađarski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="231"/>
        <source>Croatian</source>
        <translation>Hrvatski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="232"/>
        <source>Portuguese</source>
        <translation>Portugalski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="233"/>
        <source>Chinese</source>
        <translation>Kineski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="234"/>
        <source>Russian</source>
        <translation>Ruski</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="222"/>
        <source>Select a language</source>
        <translation>Izaberite jezik</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="107"/>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>Can&apos;t see your language in this list?</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="108"/>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>Help us to translate</translation>
    </message>
    <message>
        <location filename="../LanguagesSettingsTab.cpp" line="109"/>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>More information at</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../MainWindow.cpp" line="286"/>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>Zadnja konfiguracijska datoteka ne može biti otvorena. Konfiguracija izgleda bit će vraćena na staro.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="384"/>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>Želite li spremiti trenutačnu konfiguraciju prije izlaska iz Thumbnail me?</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="388"/>
        <source>saved successfully</source>
        <translation>spremanje uspješno</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="480"/>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>ne sadrľi truetype fontove. Molimo odaberite drugu mapu sa slovima u izborniku Postavke.</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="553"/>
        <source>Toolbar</source>
        <translation>Alatna traka</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="555"/>
        <source>File</source>
        <translation>Datoteka</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="556"/>
        <source>Edition</source>
        <translation>Izdanje</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="557"/>
        <source>View</source>
        <translation>Pregled</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="558"/>
        <source>Predefined Configuration</source>
        <translation>Predifinirana konfiguracija</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="559"/>
        <location filename="../MainWindow.cpp" line="576"/>
        <source>About</source>
        <translation>O</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="562"/>
        <source>Configuration</source>
        <translation>Konfiguracija</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="563"/>
        <source>Open</source>
        <translation>Otvoriti</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="564"/>
        <source>Import a configuration file</source>
        <translation>Uvezi konfiguracijsku datoteku</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="565"/>
        <source>Import a recent configuration file</source>
        <translation>Uvezi nedavno otvaranu konfiguracijsku datoteku</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="566"/>
        <source>Save my current configuration</source>
        <translation>Spremi moju trenutnu konfiguraciju</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="567"/>
        <source>Save my current configuration as</source>
        <translation>Spremi moju trenutnu konfiguraciju kao</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="568"/>
        <source>Print</source>
        <translation>Ispis</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="569"/>
        <source>Exit</source>
        <translation>Izlaz</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="570"/>
        <source>Settings</source>
        <translation>Postavke</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="571"/>
        <source>Zoom in</source>
        <translation>Približi</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="572"/>
        <source>Zoom out</source>
        <translation>Udalji</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="573"/>
        <source>Clear all</source>
        <translation>Očisti sve</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="574"/>
        <source>Fullscreen</source>
        <translation>Preko cijelog ekrana</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="575"/>
        <source>Help</source>
        <translation>Pomoć</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="577"/>
        <source>About QT</source>
        <translation>O QT-u</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="578"/>
        <source>Donate</source>
        <translation>Donirajte</translation>
    </message>
    <message>
        <location filename="../MainWindow.cpp" line="579"/>
        <source>Website</source>
        <translation>Web stranica</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="307"/>
        <source>Network Connection</source>
        <translation>Mrežno povezivanje</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="308"/>
        <source>Direct connection</source>
        <translation>Izravna veza</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="309"/>
        <source>Use proxy server</source>
        <translation>Rabi proksi poslužitelj</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="310"/>
        <source>Hostname</source>
        <translation>Naziv hosta</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="311"/>
        <source>Port</source>
        <translation>Port</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="312"/>
        <source>Type</source>
        <translation>Tip</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="313"/>
        <source>Authentication</source>
        <translation>Autentikacija</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="314"/>
        <source>Username</source>
        <translation>Korisničko ime</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="315"/>
        <source>Password</source>
        <translation>Zaporka</translation>
    </message>
    <message>
        <location filename="../NetworkSettingsTab.cpp" line="316"/>
        <source>Proxy Settings</source>
        <translation>Postavke proksija</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="324"/>
        <source>No Printer Detected</source>
        <translation>Ne Otkriven Printer</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="403"/>
        <source>Open to my default picture viewer</source>
        <translation>Otvori u mom podrazumijevanom pregledniku slika</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="404"/>
        <source>Save As</source>
        <translation>Spremi kao</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="405"/>
        <source>Copy to clipboard</source>
        <translation>Kopiraj u međuspremnik</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="261"/>
        <source>failed to open this file in your default image viewer.</source>
        <translation>nije moguće otvoriti u zadanom pregledniku slika.</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="278"/>
        <source>Save File</source>
        <translation>Spremi datoteku</translation>
    </message>
    <message>
        <location filename="../PreviewGraphicView.cpp" line="304"/>
        <source>Saving the file failed</source>
        <translation>Spremanje datoteke nije uspjelo</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="101"/>
        <source>Progression:</source>
        <translation>Napredovanje :</translation>
    </message>
    <message>
        <location filename="../ProcessingStatusBar.cpp" line="80"/>
        <source>Processing file %1 of %2: %3</source>
        <translation>Obrada datoteke %1 od %2: %3</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../main.cpp" line="92"/>
        <source>Initialisation</source>
        <translation>Inicijalizacija</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="97"/>
        <source>Widgets initialisation</source>
        <translation>Inicijalizacija widgeta</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="102"/>
        <source>Preferences reading</source>
        <translation>Očitavanje postavki</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="107"/>
        <source>Starting...</source>
        <translation>Početak...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <location filename="../SettingsWidget.cpp" line="227"/>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>OpenGL inačica 3.0 ili viša nije prisutna na vašem sustavu. Te će biti onemogućen.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="233"/>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>OpenGL nije otkriven na vašem sustavu. Te će biti onemogućen.</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="340"/>
        <source>Settings</source>
        <translation>Postavke</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="341"/>
        <source>General</source>
        <translation>Općenito</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="342"/>
        <source>Fonts</source>
        <translation>Fontovi</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="343"/>
        <source>Languages</source>
        <translation>Jezici</translation>
    </message>
    <message>
        <location filename="../SettingsWidget.cpp" line="344"/>
        <source>Network</source>
        <translation>Mreža</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <location filename="../SuccessDialog.cpp" line="226"/>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Spremi datoteku kao:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="228"/>
        <source>Upload to ImageShack</source>
        <translation>Uploadaj na ImageShack host servis</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="232"/>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Spremi datoteku(e) kao:&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="234"/>
        <source>Upload these files to ImageShack</source>
        <translation>Pošalji ove datoteke na ImageShack</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="215"/>
        <source>Open Folder</source>
        <translation>Otvori mapu</translation>
    </message>
    <message>
        <location filename="../SuccessDialog.cpp" line="216"/>
        <source>Close</source>
        <translation>Zatvori</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="116"/>
        <location filename="../ThumbnailEngine.cpp" line="126"/>
        <location filename="../ThumbnailEngine.cpp" line="143"/>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Mtn binarno nije pronađeno. Operacija otkazana.</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="117"/>
        <location filename="../ThumbnailEngine.cpp" line="127"/>
        <location filename="../ThumbnailEngine.cpp" line="144"/>
        <source>No fonts defined</source>
        <translation>Nema definiranih fontova</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="118"/>
        <source>Output path does not exist</source>
        <translation>Izlazna putanja ne postoji</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="119"/>
        <source>Select an output folder, please</source>
        <translation>Odaberite izlaznu mapu, molim</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="130"/>
        <source>No file(s) loaded</source>
        <translation>Nema učitanih datoteka(e)</translation>
    </message>
    <message>
        <location filename="../ThumbnailEngine.cpp" line="145"/>
        <source>No file selected</source>
        <translation>Datoteka nije izabrana</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <location filename="../ThumbnailListwidget.cpp" line="105"/>
        <source>You must select a file to remove it from the list</source>
        <translation>Morate izabrati datoteku da biste je uklonili s popisa</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <location filename="../VerboseWindow.cpp" line="41"/>
        <location filename="../VerboseWindow.cpp" line="142"/>
        <source>Copy to clipboard</source>
        <translation>Kopiraj u međuspremnik</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="141"/>
        <source>Logs</source>
        <translation>Dnevnik</translation>
    </message>
    <message>
        <location filename="../VerboseWindow.cpp" line="38"/>
        <location filename="../VerboseWindow.cpp" line="143"/>
        <source>Clear all</source>
        <translation>Obriši sve</translation>
    </message>
</context>
</TS>
