<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="it">
<context>
    <name>About</name>
    <message>
        <source>About</source>
        <translation>Info</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <source>Copy to clipboard</source>
        <translation>Copia negli Appunti</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <source>Gap</source>
        <translation>Vuoto</translation>
    </message>
    <message>
        <source>Rows</source>
        <translation>Righe</translation>
    </message>
    <message>
        <source>Width</source>
        <translation>Altezza</translation>
    </message>
    <message>
        <source>Edge detection</source>
        <translation>Bordo di Rilevamento</translation>
    </message>
    <message>
        <source>Output Format</source>
        <translation>Formato Destinazione</translation>
    </message>
    <message>
        <source>Blank skip</source>
        <translation>Vuoto da Saltare</translation>
    </message>
    <message>
        <source>Configuration</source>
        <translation>Configurazione</translation>
    </message>
    <message>
        <source>Quality</source>
        <translation>Qualità</translation>
    </message>
    <message>
        <source>Columns</source>
        <translation>Colonne</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <source>Path Output</source>
        <translation>Cartella di Destinazione</translation>
    </message>
    <message>
        <source>Same folder output as source</source>
        <translation>Usa come cartella di destinazione la stessa di origine</translation>
    </message>
    <message>
        <source>Media list is already empty</source>
        <translation>L&apos;elenco dei media è già vuoto</translation>
    </message>
    <message>
        <source>Input and Output</source>
        <translation>Input e Output</translation>
    </message>
    <message>
        <source>Load</source>
        <translation>Carica</translation>
    </message>
    <message>
        <source>Reset</source>
        <translation>Reset</translation>
    </message>
    <message>
        <source>Delete Selection</source>
        <translation>Cancella Selezione</translation>
    </message>
    <message>
        <source>Preview selection file</source>
        <translation>Anteprima file selezionato</translation>
    </message>
    <message>
        <source>Start</source>
        <translation>Converti</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <source>Timestamp</source>
        <translation>Tempo</translation>
    </message>
    <message>
        <source>Upper Right</source>
        <translation>In alto a destra</translation>
    </message>
    <message>
        <source>Lower Right</source>
        <translation>In basso a destra</translation>
    </message>
    <message>
        <source>Styles</source>
        <translation>Stili</translation>
    </message>
    <message>
        <source>Generated by Thumbnail me</source>
        <translation>Creato con Thumbnail me</translation>
    </message>
    <message>
        <source>Building Font Cache...</source>
        <translation>Caricando i Font...</translation>
    </message>
    <message>
        <source>Background Color</source>
        <translation>Colore dello Sfondo</translation>
    </message>
    <message>
        <source>Lower Left</source>
        <translation>In basso a sinistra</translation>
    </message>
    <message>
        <source>Upper Left</source>
        <translation>In alto a sinistra</translation>
    </message>
    <message>
        <source>Shadow Color</source>
        <translation>Ombreggiatura del Colore</translation>
    </message>
    <message>
        <source>Info Text</source>
        <translation>Info Testo</translation>
    </message>
    <message>
        <source>Additional Title</source>
        <translation>Titolo Addizionale</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <source>To</source>
        <translation>A</translation>
    </message>
    <message>
        <source>From</source>
        <translation>Da</translation>
    </message>
    <message>
        <source>TimeLine</source>
        <translation>Linea del Tempo</translation>
    </message>
    <message>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>Impossibile creare la linea del tempo | File non supportato</translation>
    </message>
    <message>
        <source>Total duration</source>
        <translation>Durata Totale</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <source>No fonts defined</source>
        <translation>Nessun carattere specificato</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <source>Add</source>
        <translation>Aggiungi</translation>
    </message>
    <message>
        <source>Remove</source>
        <translation>Rimuovi</translation>
    </message>
    <message>
        <source>No fonts found in this folder</source>
        <translation>Non sono stati trovati caratteri in questa cartella</translation>
    </message>
    <message>
        <source>Select a font folder</source>
        <translation>Seleziona una cartella contenente caratteri</translation>
    </message>
    <message>
        <source>You must select a path to remove it from the list</source>
        <translation>Devi selezionare un percorso per rimuovere questo dalla lista</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <source>General Settings</source>
        <translation>Impostazioni Generali</translation>
    </message>
    <message>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>Non caricare la mia configurazione all&apos;avvio</translation>
    </message>
    <message>
        <source>Output suffix:</source>
        <translation>Suffisso di Output :</translation>
    </message>
    <message>
        <source>Activate openGL to preview thumbnails</source>
        <translation>Attiva openGL per visualizzare in anteprima le anteprime</translation>
    </message>
    <message>
        <source>Animate pixmap while rendering</source>
        <translation>Animare l&apos;immagine durante la produzione</translation>
    </message>
    <message>
        <source>Background color of preview window</source>
        <translation>Colore di sfondo per le anteprime</translation>
    </message>
    <message>
        <source>Never ask me to save my configuration on exit</source>
        <translation>Non chiedere mai di salvare la mia configurazione prima di uscire</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <source>Help</source>
        <translation>Aiuto</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <source>Login</source>
        <translation>Login</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Annulla</translation>
    </message>
    <message>
        <source>Logout</source>
        <translation>Esci</translation>
    </message>
    <message>
        <source>Login as</source>
        <translation>Entra come...</translation>
    </message>
    <message>
        <source>Password</source>
        <translation>Password</translation>
    </message>
    <message>
        <source>Authentication failed. Check your username and password.</source>
        <translation>Autenticazione fallita. Controlla il tuo Nome Utente e la tua Password.</translation>
    </message>
    <message>
        <source>Autologin</source>
        <translation>Login Automatico</translation>
    </message>
    <message>
        <source>Remember Password</source>
        <translation>Ricorda la password</translation>
    </message>
    <message>
        <source>Login in progress...</source>
        <translation>Eseguendo il Login...</translation>
    </message>
    <message>
        <source>Username/E-mail</source>
        <translation>Nome Utente/E-Mail</translation>
    </message>
    <message>
        <source>Connection refused</source>
        <translation>Connessione rifiutata</translation>
    </message>
    <message>
        <source>Remote host closed</source>
        <translation>Indirizzo remoto non raggiungibile</translation>
    </message>
    <message>
        <source>Host not found</source>
        <translation>Host non trovato</translation>
    </message>
    <message>
        <source>Timeout</source>
        <translation>Timeout</translation>
    </message>
    <message>
        <source>Operation canceled</source>
        <translation>Operazione annullata</translation>
    </message>
    <message>
        <source>SSL handshake failed</source>
        <translation>Handshake SLL fallito</translation>
    </message>
    <message>
        <source>Proxy connection refused</source>
        <translation>Connessione Proxy Rifiutata</translation>
    </message>
    <message>
        <source>Proxy connection closed</source>
        <translation>Connessione proxy chiusa</translation>
    </message>
    <message>
        <source>Proxy not found</source>
        <translation>Server proxy non trovato</translation>
    </message>
    <message>
        <source>Proxy timeout</source>
        <translation>Timeout del Proxy</translation>
    </message>
    <message>
        <source>Proxy authentication required</source>
        <translation>Autenticazione Proxy richiesta</translation>
    </message>
    <message>
        <source>Content access denied</source>
        <translation>Accesso al Contenuto Negato</translation>
    </message>
    <message>
        <source>Content operation not permitted</source>
        <translation>Operazione sui contenuti non permessa</translation>
    </message>
    <message>
        <source>Content not found</source>
        <translation>Contenuto non trovato</translation>
    </message>
    <message>
        <source>Authentication required</source>
        <translation>Autenticazione Richiesta</translation>
    </message>
    <message>
        <source>Protocol unknown</source>
        <translation>Protocollo sconosciuto</translation>
    </message>
    <message>
        <source>Protocol invalid operation</source>
        <translation>Operazione non valida sul protocollo</translation>
    </message>
    <message>
        <source>Unknown network</source>
        <translation>Network sconosciuto</translation>
    </message>
    <message>
        <source>Unknown proxy</source>
        <translation>Proxy sconosciuto</translation>
    </message>
    <message>
        <source>Unknown content</source>
        <translation>Contenuto sconosciuto</translation>
    </message>
    <message>
        <source>Protocol failure</source>
        <translation>Fallimento del protocollo</translation>
    </message>
    <message>
        <source>Content resend</source>
        <translation>Contenuto Reinviato</translation>
    </message>
    <message>
        <source>Temporary network failure</source>
        <translation>Network temporaneo fallito</translation>
    </message>
    <message>
        <source>Unknown error</source>
        <translation>Errore sconosciuto</translation>
    </message>
    <message>
        <source>Failed to open the file</source>
        <translation>Impossibile aprire il file</translation>
    </message>
    <message>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Massima dimensione raggiunta (5 MB)</translation>
    </message>
    <message>
        <source>Upload Error:</source>
        <translation>Errore di Caricamento :</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <source>Close</source>
        <translation>Chiudi</translation>
    </message>
    <message>
        <source>Uploaded files</source>
        <translation>File Caricati</translation>
    </message>
    <message>
        <source>File 1 of 1</source>
        <translation>File 1 di 1</translation>
    </message>
    <message>
        <source>Thumbnail for forums 1</source>
        <translation>Anteprima per Forum 1</translation>
    </message>
    <message>
        <source>Thumbnail for forums 2</source>
        <translation>Anteprima per Forum 2</translation>
    </message>
    <message>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink per Forum 1</translation>
    </message>
    <message>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink per Forum 2</translation>
    </message>
    <message>
        <source>Thumbnail for web</source>
        <translation>Anteprima per il Web</translation>
    </message>
    <message>
        <source>Hotlink for web</source>
        <translation>Hotlink per il Web</translation>
    </message>
    <message>
        <source>Short link</source>
        <translation>Link Corto</translation>
    </message>
    <message>
        <source>Direct link</source>
        <translation>Link Diretto</translation>
    </message>
    <message>
        <source>File %1 of %2</source>
        <translation>File %1 di %2</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <source>Processing file %1 of %2</source>
        <translation>Creando i file %1 di %2</translation>
    </message>
    <message>
        <source>login</source>
        <translation>login</translation>
    </message>
    <message>
        <source>Proxy not found</source>
        <translation>Server proxy non trovato</translation>
    </message>
    <message>
        <source>Host not found</source>
        <translation>Host non trovato</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Modalità di Upload: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (per internet e mail)</translation>
    </message>
    <message>
        <source>Protocol unknown</source>
        <translation>Protocollo sconosciuto</translation>
    </message>
    <message>
        <source>Comma separated list</source>
        <translation>Elenco separato da virgole</translation>
    </message>
    <message>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Image resize:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Content resend</source>
        <translation>Contenuto Reinviato</translation>
    </message>
    <message>
        <source>Proxy connection refused</source>
        <translation>Connessione Proxy Rifiutata</translation>
    </message>
    <message>
        <source>File upload progress:</source>
        <translation>Progresso del caricamento :</translation>
    </message>
    <message>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (monitor a 12 pollici)</translation>
    </message>
    <message>
        <source>Failed to open the file</source>
        <translation>Impossibile aprire il file</translation>
    </message>
    <message>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (monitor a 19 pollici)</translation>
    </message>
    <message>
        <source>100x100 (avatar)</source>
        <translation>100x100 (avatar)</translation>
    </message>
    <message>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Massima dimensione raggiunta (5 MB)</translation>
    </message>
    <message>
        <source>Upload mode:</source>
        <translation>Modalità di Upload :</translation>
    </message>
    <message>
        <source>Remote host closed</source>
        <translation>Indirizzo remoto non raggiungibile</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Annulla</translation>
    </message>
    <message>
        <source>Content access denied</source>
        <translation>Accesso al Contenuto Negato</translation>
    </message>
    <message>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (anteprima)</translation>
    </message>
    <message>
        <source>Upload now</source>
        <translation>Carica ora</translation>
    </message>
    <message>
        <source>Public</source>
        <translation>Pubblica</translation>
    </message>
    <message>
        <source>Log in to use these features</source>
        <translation>Accedi per utilizzare queste funzioni</translation>
    </message>
    <message>
        <source>Temporary network failure</source>
        <translation>Network temporaneo fallito</translation>
    </message>
    <message>
        <source>Proxy connection closed</source>
        <translation>Connessione proxy chiusa</translation>
    </message>
    <message>
        <source>anonymous</source>
        <translation>Anonimo</translation>
    </message>
    <message>
        <source>Unknown network</source>
        <translation>Network sconosciuto</translation>
    </message>
    <message>
        <source>Connection refused</source>
        <translation>Connessione rifiutata</translation>
    </message>
    <message>
        <source>Protocol failure</source>
        <translation>Fallimento del protocollo</translation>
    </message>
    <message>
        <source>Proxy authentication required</source>
        <translation>Autenticazione Proxy richiesta</translation>
    </message>
    <message>
        <source>Total upload progress:</source>
        <translation>Progresso Caricamento Totale :</translation>
    </message>
    <message>
        <source>Private</source>
        <translation>Privato</translation>
    </message>
    <message>
        <source>Upload Error:</source>
        <translation>Errore di Caricamento :</translation>
    </message>
    <message>
        <source>File loaded: %1</source>
        <translation>File Caricati: %1</translation>
    </message>
    <message>
        <source>Log in to use this features</source>
        <translation>Accedi per utilizzare queste funzioni</translation>
    </message>
    <message>
        <source>Protocol invalid operation</source>
        <translation>Operazione non valida sul protocollo</translation>
    </message>
    <message>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (monitor a 15 pollici)</translation>
    </message>
    <message>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Privacy:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Operation canceled</source>
        <translation>Operazione annullata</translation>
    </message>
    <message>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Etichette:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Content not found</source>
        <translation>Contenuto non trovato</translation>
    </message>
    <message>
        <source>Authentication required</source>
        <translation>Autenticazione Richiesta</translation>
    </message>
    <message>
        <source>SSL handshake failed</source>
        <translation>Handshake SLL fallito</translation>
    </message>
    <message>
        <source>Content operation not permitted</source>
        <translation>Operazione sui contenuti non permessa</translation>
    </message>
    <message>
        <source>Timeout</source>
        <translation>Timeout</translation>
    </message>
    <message>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (per bacheche)</translation>
    </message>
    <message>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (monitor a 21 pollici)</translation>
    </message>
    <message>
        <source>File(s) loaded: %1</source>
        <translation>File(s) caricati: %1</translation>
    </message>
    <message>
        <source>Upload in progress...</source>
        <translation>Caricando...</translation>
    </message>
    <message>
        <source>Unknown content</source>
        <translation>Contenuto sconosciuto</translation>
    </message>
    <message>
        <source>Unknown proxy</source>
        <translation>Proxy sconosciuto</translation>
    </message>
    <message>
        <source>Unknown error</source>
        <translation>Errore sconosciuto</translation>
    </message>
    <message>
        <source>Do not resize</source>
        <translation>Non Ridimensionare</translation>
    </message>
    <message>
        <source>Proxy timeout</source>
        <translation>Timeout del Proxy</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Richiesta autenticazione per impostare Tag e Privacy nella tua anteprima&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <source>Save Configuration File</source>
        <translation>Salva File di Configurazione</translation>
    </message>
    <message>
        <source>Open Configuration File</source>
        <translation>Apri Configurazione File</translation>
    </message>
    <message>
        <source>Configuration file</source>
        <translation>File di Configurazione</translation>
    </message>
    <message>
        <source>Configuration file loaded</source>
        <translation>File di Configurazione Caricato</translation>
    </message>
    <message>
        <source>Not recent files</source>
        <translation>Nessun File Recente</translation>
    </message>
    <message>
        <source> saved successfully</source>
        <translation> Salvato con Successo</translation>
    </message>
    <message>
        <source>Configuration file(*.ini)</source>
        <translation>File di Configurazione(*.ini)</translation>
    </message>
    <message>
        <source>Incorrect settings file</source>
        <translation>Impostazioni del file sbagliate</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <source>Dutch</source>
        <translation>Olandese</translation>
    </message>
    <message>
        <source>French</source>
        <translation>Francese</translation>
    </message>
    <message>
        <source>German</source>
        <translation>Tedesco</translation>
    </message>
    <message>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <source>Spanish</source>
        <translation>Spagnolo</translation>
    </message>
    <message>
        <source>English</source>
        <translation>Inglese</translation>
    </message>
    <message>
        <source>Select a language</source>
        <translation>Seleziona una Lingua</translation>
    </message>
    <message>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation></translation>
    </message>
    <message>
        <source>Italian</source>
        <translation>Italiano</translation>
    </message>
    <message>
        <source>Czech</source>
        <translation>Ceco</translation>
    </message>
    <message>
        <source>Hungarian</source>
        <translation>Ungherese</translation>
    </message>
    <message>
        <source>Croatian</source>
        <translation>Croato</translation>
    </message>
    <message>
        <source>Portuguese</source>
        <translation>Portoghese</translation>
    </message>
    <message>
        <source>Chinese</source>
        <translation>Cinese</translation>
    </message>
    <message>
        <source>Russian</source>
        <translation>Russo</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>Impossibile caricare la precedente configurazione. La configurazione del layout sarà reimpostata.</translation>
    </message>
    <message>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>Vuoi salvare l&apos;attuale configurazione prima di uscire da Thumbnail me?</translation>
    </message>
    <message>
        <source>saved successfully</source>
        <translation>salvata con Successo</translation>
    </message>
    <message>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>Impossibile trovare file di caratteri. Scegliere un&apos;altra cartella dal menù impostazioni.</translation>
    </message>
    <message>
        <source>Toolbar</source>
        <translation>Barra degli Strumenti</translation>
    </message>
    <message>
        <source>File</source>
        <translation>File</translation>
    </message>
    <message>
        <source>Edition</source>
        <translation>Modifica</translation>
    </message>
    <message>
        <source>View</source>
        <translation>Anteprima</translation>
    </message>
    <message>
        <source>Predefined Configuration</source>
        <translation>Configurazione Predefinita</translation>
    </message>
    <message>
        <source>About</source>
        <translation>Info</translation>
    </message>
    <message>
        <source>Configuration</source>
        <translation>Configurazione</translation>
    </message>
    <message>
        <source>Open</source>
        <translation>Apri</translation>
    </message>
    <message>
        <source>Import a configuration file</source>
        <translation>Importa File di Configurazione</translation>
    </message>
    <message>
        <source>Import a recent configuration file</source>
        <translation>Importa un File di Configurazione Recente</translation>
    </message>
    <message>
        <source>Save my current configuration</source>
        <translation>Salva la Configurazione Corrente</translation>
    </message>
    <message>
        <source>Save my current configuration as</source>
        <translation>Salva la mia configurazione corrente come...</translation>
    </message>
    <message>
        <source>Print</source>
        <translation>Stampa</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation>Esci</translation>
    </message>
    <message>
        <source>Settings</source>
        <translation>Impostazioni</translation>
    </message>
    <message>
        <source>Zoom in</source>
        <translation>Aumenta lo Zoom</translation>
    </message>
    <message>
        <source>Zoom out</source>
        <translation>Diminuisci lo Zoom</translation>
    </message>
    <message>
        <source>Clear all</source>
        <translation>Pulisci Tutto</translation>
    </message>
    <message>
        <source>Fullscreen</source>
        <translation>A tutto schermo</translation>
    </message>
    <message>
        <source>Help</source>
        <translation>Aiuto</translation>
    </message>
    <message>
        <source>About QT</source>
        <translation>Info su QT</translation>
    </message>
    <message>
        <source>Donate</source>
        <translation>Fai una Donazione</translation>
    </message>
    <message>
        <source>Website</source>
        <translation>Sito Web</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <source>Port</source>
        <translation>Porta</translation>
    </message>
    <message>
        <source>Type</source>
        <translation>Tipo</translation>
    </message>
    <message>
        <source>Use proxy server</source>
        <translation>Usa Server Proxy</translation>
    </message>
    <message>
        <source>Authentication</source>
        <translation>Autenticazione</translation>
    </message>
    <message>
        <source>Proxy Settings</source>
        <translation>Impostazioni Proxy</translation>
    </message>
    <message>
        <source>Hostname</source>
        <translation>Nome Host</translation>
    </message>
    <message>
        <source>Password</source>
        <translation>Password</translation>
    </message>
    <message>
        <source>Network Connection</source>
        <translation>Connessione di Rete</translation>
    </message>
    <message>
        <source>Username</source>
        <translation>Nome Utente</translation>
    </message>
    <message>
        <source>Direct connection</source>
        <translation>Connessione Diretta</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <source>Saving the file failed</source>
        <translation>Impossibile Salvare il File</translation>
    </message>
    <message>
        <source>Copy to clipboard</source>
        <translation>Copia negli Appunti</translation>
    </message>
    <message>
        <source>Open to my default picture viewer</source>
        <translation>Apri con il visualizzatore di foto predefinito</translation>
    </message>
    <message>
        <source>Save As</source>
        <translation>Salva come</translation>
    </message>
    <message>
        <source>failed to open this file in your default image viewer.</source>
        <translation>Impossibile aprire il file nel visualizzatore di foto predefinito.</translation>
    </message>
    <message>
        <source>Save File</source>
        <translation>Salva File</translation>
    </message>
    <message>
        <source>No Printer Detected</source>
        <translation>Nessuna stampante trovata</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <source>Processing file %1 of %2: %3</source>
        <translation>Elaborando i file %1 di %2: %3</translation>
    </message>
    <message>
        <source>Progression:</source>
        <translation>Progresso :</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Preferences reading</source>
        <translation>Caricando le Preferenze</translation>
    </message>
    <message>
        <source>Initialisation</source>
        <translation>Inizializzazione</translation>
    </message>
    <message>
        <source>Widgets initialisation</source>
        <translation>Inizializzazione Widget</translation>
    </message>
    <message>
        <source>Starting...</source>
        <translation>Avviando...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <source>Fonts</source>
        <translation>Caratteri</translation>
    </message>
    <message>
        <source>Network</source>
        <translation>Rete</translation>
    </message>
    <message>
        <source>Languages</source>
        <translation>Lingue</translation>
    </message>
    <message>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>Una versione di OpenGL 3.0 o superiore non è presente nel sistema. La funzione sarà disabilitata.</translation>
    </message>
    <message>
        <source>Settings</source>
        <translation>Impostazioni</translation>
    </message>
    <message>
        <source>General</source>
        <translation>Generale</translation>
    </message>
    <message>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>OpenGL non è presente nel sistema. La funzione sarà disabilitata.</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <source>Close</source>
        <translation>Chiudi</translation>
    </message>
    <message>
        <source>Upload these files to ImageShack</source>
        <translation>Carica questi file su ImageShack</translation>
    </message>
    <message>
        <source>Upload to ImageShack</source>
        <translation>Carica su ImageShack</translation>
    </message>
    <message>
        <source>Open Folder</source>
        <translation>Apri Cartella</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Salva File come:&lt;/h1&gt;</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Salva i File come:&lt;/h1&gt;</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <source>Select an output folder, please</source>
        <translation>Selezionare una cartella di output</translation>
    </message>
    <message>
        <source>No file selected</source>
        <translation>Nessun File Selezionato</translation>
    </message>
    <message>
        <source>No file(s) loaded</source>
        <translation>Nessun File Caricato</translation>
    </message>
    <message>
        <source>No fonts defined</source>
        <translation>Nessun carattere selezionato</translation>
    </message>
    <message>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Mtn binario non trovato. Operazione annullata.</translation>
    </message>
    <message>
        <source>Output path does not exist</source>
        <translation>La cartella di destinazione non esiste</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <source>You must select a file to remove it from the list</source>
        <translation>Devi selezionare un file per rimuovere questo dalla lista</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <source>Logs</source>
        <translation>Report</translation>
    </message>
    <message>
        <source>Clear all</source>
        <translation>Pulisci Tutto</translation>
    </message>
    <message>
        <source>Copy to clipboard</source>
        <translation>Copia negli Appunti</translation>
    </message>
</context>
</TS>
