<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="hu_HU" sourcelanguage="en">
<context>
    <name>About</name>
    <message>
        <source>About</source>
        <translation>Névjegy</translation>
    </message>
</context>
<context>
    <name>CopyableLineEdit</name>
    <message>
        <source>Copy to clipboard</source>
        <translation>Másolás a vágólapra</translation>
    </message>
</context>
<context>
    <name>DockConf</name>
    <message>
        <source>Gap</source>
        <translation>Köz</translation>
    </message>
    <message>
        <source>Rows</source>
        <translation>Sorok</translation>
    </message>
    <message>
        <source>Width</source>
        <translation>Szélesség</translation>
    </message>
    <message>
        <source>Edge detection</source>
        <translation>Élek észlelése</translation>
    </message>
    <message>
        <source>Output Format</source>
        <translation>Kimeneti formátum</translation>
    </message>
    <message>
        <source>Blank skip</source>
        <translation>Üres kihagyása</translation>
    </message>
    <message>
        <source>Configuration</source>
        <translation>Konfiguráció</translation>
    </message>
    <message>
        <source>Quality</source>
        <translation>Minőség</translation>
    </message>
    <message>
        <source>Columns</source>
        <translation>Oszlopok</translation>
    </message>
</context>
<context>
    <name>DockInputOutput</name>
    <message>
        <source>Path Output</source>
        <translation>Kimeneti hely</translation>
    </message>
    <message>
        <source>Same folder output as source</source>
        <translation>A forrásállománnyal megegyező mappa</translation>
    </message>
    <message>
        <source>Media list is already empty</source>
        <translation>A média lista már üres</translation>
    </message>
    <message>
        <source>Input and Output</source>
        <translation>Bemenet és kimenet</translation>
    </message>
    <message>
        <source>Load</source>
        <translation>Betöltés</translation>
    </message>
    <message>
        <source>Reset</source>
        <translation>Alaphelyzet</translation>
    </message>
    <message>
        <source>Delete Selection</source>
        <translation>Kijelölt törlése</translation>
    </message>
    <message>
        <source>Preview selection file</source>
        <translation>Kiválasztott fájl előnézete</translation>
    </message>
    <message>
        <source>Start</source>
        <translation>Indítás</translation>
    </message>
</context>
<context>
    <name>DockStyles</name>
    <message>
        <source>Timestamp</source>
        <translation>Időbélyegző</translation>
    </message>
    <message>
        <source>Upper Right</source>
        <translation>Jobb felső</translation>
    </message>
    <message>
        <source>Lower Right</source>
        <translation>Jobb alsó</translation>
    </message>
    <message>
        <source>Styles</source>
        <translation>Stílusok</translation>
    </message>
    <message>
        <source>Generated by Thumbnail me</source>
        <translation>Készült a Thumbnail me programmal</translation>
    </message>
    <message>
        <source>Building Font Cache...</source>
        <translation>Betűtípus-gyorsítótár létrehozása...</translation>
    </message>
    <message>
        <source>Background Color</source>
        <translation>Háttérszín</translation>
    </message>
    <message>
        <source>Lower Left</source>
        <translation>Bal alsó</translation>
    </message>
    <message>
        <source>Upper Left</source>
        <translation>Bal felső</translation>
    </message>
    <message>
        <source>Shadow Color</source>
        <translation>Árnyék színe</translation>
    </message>
    <message>
        <source>Info Text</source>
        <translation>Információs szöveg</translation>
    </message>
    <message>
        <source>Additional Title</source>
        <translation>Kiegészítő cím</translation>
    </message>
</context>
<context>
    <name>DockTimeLine</name>
    <message>
        <source>To</source>
        <translation>Eddig</translation>
    </message>
    <message>
        <source>From</source>
        <translation>Ettől</translation>
    </message>
    <message>
        <source>TimeLine</source>
        <translation>Idővonal</translation>
    </message>
    <message>
        <source>TimeLine (Not available) | Media isn&apos;t fully supported</source>
        <translation>Idővonal (Nem elérhető) | A média nem teljesen támogatott</translation>
    </message>
    <message>
        <source>Total duration</source>
        <translation>Teljes időtartam</translation>
    </message>
</context>
<context>
    <name>FontMapComboBox</name>
    <message>
        <source>No fonts defined</source>
        <translation>Nincs betűtípus megadva</translation>
    </message>
</context>
<context>
    <name>FontsSettingsTab</name>
    <message>
        <source>Add</source>
        <translation>Hozzáadás</translation>
    </message>
    <message>
        <source>Remove</source>
        <translation>Eltávolítás</translation>
    </message>
    <message>
        <source>No fonts found in this folder</source>
        <translation>Nem találhatók betűtípusok ebben a mappában</translation>
    </message>
    <message>
        <source>Select a font folder</source>
        <translation>Válassza ki a betűtípus-mappát</translation>
    </message>
    <message>
        <source>You must select a path to remove it from the list</source>
        <translation>Ki kell választania egy helyet a listából való eltávolításához</translation>
    </message>
</context>
<context>
    <name>GeneralSettingsTab</name>
    <message>
        <source>General Settings</source>
        <translation>Általános beállítások</translation>
    </message>
    <message>
        <source>Don&apos;t load the last configuration on startup</source>
        <translation>Ne töltse be az utolsó konfigurációt indításkor</translation>
    </message>
    <message>
        <source>Output suffix:</source>
        <translation>Kimeneti utótag :</translation>
    </message>
    <message>
        <source>Activate openGL to preview thumbnails</source>
        <translation>Az OpenGL aktiválása a bélyegképek megtekintéséhez</translation>
    </message>
    <message>
        <source>Animate pixmap while rendering</source>
        <translation>Pixmap animálás leképezés közben</translation>
    </message>
    <message>
        <source>Background color of preview window</source>
        <translation>Előnézeti ablak háttérszíne</translation>
    </message>
    <message>
        <source>Never ask me to save my configuration on exit</source>
        <translation>Soha ne kérdezzen rá a konfigurációm mentésére kilépéskor</translation>
    </message>
</context>
<context>
    <name>HelpWidget</name>
    <message>
        <source>Help</source>
        <translation>Súgó</translation>
    </message>
</context>
<context>
    <name>ImageShackLoginWidget</name>
    <message>
        <source>Login</source>
        <translation>Bejelentkezés</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Mégse</translation>
    </message>
    <message>
        <source>Logout</source>
        <translation>Kilépés</translation>
    </message>
    <message>
        <source>Login as</source>
        <translation>Bejelentkezés mint</translation>
    </message>
    <message>
        <source>Password</source>
        <translation>Jelszó</translation>
    </message>
    <message>
        <source>Authentication failed. Check your username and password.</source>
        <translation>A hitelesítés sikertelen. Ellenőrizze a felhasználónevet és a jelszót.</translation>
    </message>
    <message>
        <source>Autologin</source>
        <translation>Automatikus belépés</translation>
    </message>
    <message>
        <source>Remember Password</source>
        <translation>Jelszó tárolása</translation>
    </message>
    <message>
        <source>Login in progress...</source>
        <translation>Bejelentkezés folyamatban...</translation>
    </message>
    <message>
        <source>Username/E-mail</source>
        <translation>Felhasználónév/E-mail</translation>
    </message>
    <message>
        <source>Connection refused</source>
        <translation>Kapcsolat elutasítva</translation>
    </message>
    <message>
        <source>Remote host closed</source>
        <translation>Távoli állomás lezárva</translation>
    </message>
    <message>
        <source>Host not found</source>
        <translation>Host nem található</translation>
    </message>
    <message>
        <source>Timeout</source>
        <translation>Időtúllépés</translation>
    </message>
    <message>
        <source>Operation canceled</source>
        <translation>Művelet megszakítva</translation>
    </message>
    <message>
        <source>SSL handshake failed</source>
        <translation>Sikertelen SSL handshake művelet</translation>
    </message>
    <message>
        <source>Proxy connection refused</source>
        <translation>Proxy kapcsolat elutasítva</translation>
    </message>
    <message>
        <source>Proxy connection closed</source>
        <translation>Proxy kapcsolat lezárva</translation>
    </message>
    <message>
        <source>Proxy not found</source>
        <translation>A proxy nem található</translation>
    </message>
    <message>
        <source>Proxy timeout</source>
        <translation>Proxy időtúllépés</translation>
    </message>
    <message>
        <source>Proxy authentication required</source>
        <translation>Proxyhitelesítés szükséges</translation>
    </message>
    <message>
        <source>Content access denied</source>
        <translation>Tartalom hozzáférés megtagadva</translation>
    </message>
    <message>
        <source>Content operation not permitted</source>
        <translation>A tartalmi művelet nem engedélyezett</translation>
    </message>
    <message>
        <source>Content not found</source>
        <translation>A tartalom nem található</translation>
    </message>
    <message>
        <source>Authentication required</source>
        <translation>Hitelesítés szükséges</translation>
    </message>
    <message>
        <source>Protocol unknown</source>
        <translation>Ismeretlen protokoll</translation>
    </message>
    <message>
        <source>Protocol invalid operation</source>
        <translation>Érvénytelen protokoll művelet</translation>
    </message>
    <message>
        <source>Unknown network</source>
        <translation>Ismeretlen hálózat</translation>
    </message>
    <message>
        <source>Unknown proxy</source>
        <translation>Ismeretlen proxy</translation>
    </message>
    <message>
        <source>Unknown content</source>
        <translation>Ismeretlen tartalom</translation>
    </message>
    <message>
        <source>Protocol failure</source>
        <translation>Protokollhiba</translation>
    </message>
    <message>
        <source>Content resend</source>
        <translation>Tartalom újraküldése</translation>
    </message>
    <message>
        <source>Temporary network failure</source>
        <translation>Ideiglenes hálózati hiba</translation>
    </message>
    <message>
        <source>Unknown error</source>
        <translation>Ismeretlen hiba</translation>
    </message>
    <message>
        <source>Failed to open the file</source>
        <translation>Nem sikerült megnyitni a fájlt</translation>
    </message>
    <message>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Elérte a maximális méretet (5 Mb)</translation>
    </message>
    <message>
        <source>Upload Error:</source>
        <translation>Feltöltési hiba :</translation>
    </message>
</context>
<context>
    <name>ImageShackResultWidget</name>
    <message>
        <source>Close</source>
        <translation>Bezárás</translation>
    </message>
    <message>
        <source>Uploaded files</source>
        <translation>Feltöltött fájlok</translation>
    </message>
    <message>
        <source>File 1 of 1</source>
        <translation>1 - 1 fájl</translation>
    </message>
    <message>
        <source>Thumbnail for forums 1</source>
        <translation>Bélyegkép az 1. fórumra</translation>
    </message>
    <message>
        <source>Thumbnail for forums 2</source>
        <translation>Bélyegkép a 2. fórumra</translation>
    </message>
    <message>
        <source>Hotlink for forums 1</source>
        <translation>Hotlink az 1. fórumra</translation>
    </message>
    <message>
        <source>Hotlink for forums 2</source>
        <translation>Hotlink a 2. fórumra</translation>
    </message>
    <message>
        <source>Thumbnail for web</source>
        <translation>Bélyegkép a webre</translation>
    </message>
    <message>
        <source>Hotlink for web</source>
        <translation>Hotlink a webre</translation>
    </message>
    <message>
        <source>Short link</source>
        <translation>Rövid hivatkozás</translation>
    </message>
    <message>
        <source>Direct link</source>
        <translation>Közvetlen hivatkozás</translation>
    </message>
    <message>
        <source>File %1 of %2</source>
        <translation>%1 - %2 fájl</translation>
    </message>
</context>
<context>
    <name>ImageShackUploadWidget</name>
    <message>
        <source>Processing file %1 of %2</source>
        <translation>%1 - %2 fájl feldolgozása</translation>
    </message>
    <message>
        <source>login</source>
        <translation>bejelentkezés</translation>
    </message>
    <message>
        <source>Proxy not found</source>
        <translation>A proxy nem található</translation>
    </message>
    <message>
        <source>Host not found</source>
        <translation>Host nem található</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Upload mode: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;anonymous&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Feltöltési mód: &lt;/span&gt;&lt;span style=&quot; font-size:8pt; color:#ff0000;&quot;&gt;névtelen&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>320x320 (for websites and email)</source>
        <translation>320x320 (weboldalakakhoz és emailekhez)</translation>
    </message>
    <message>
        <source>Protocol unknown</source>
        <translation>Ismeretlen protokoll</translation>
    </message>
    <message>
        <source>Comma separated list</source>
        <translation>Vesszővel elválasztott lista</translation>
    </message>
    <message>
        <source>&lt;b&gt;Image resize:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Kép átméretezése:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Content resend</source>
        <translation>Tartalom újraküldése</translation>
    </message>
    <message>
        <source>Proxy connection refused</source>
        <translation>Proxy kapcsolat elutasítva</translation>
    </message>
    <message>
        <source>File upload progress:</source>
        <translation>Fájl feltöltési folyamat :</translation>
    </message>
    <message>
        <source>800x800 (12-inch monitor)</source>
        <translation>800x800 (12-colos monitor)</translation>
    </message>
    <message>
        <source>Failed to open the file</source>
        <translation>Nem sikerült megnyitni a fájlt</translation>
    </message>
    <message>
        <source>1280x1280 (19-inch monitor)</source>
        <translation>1280x1280 (19-colos monitor)</translation>
    </message>
    <message>
        <source>100x100 (avatar)</source>
        <translation>100x100 (avatár)</translation>
    </message>
    <message>
        <source>Max Size Reached (5 Mb)</source>
        <translation>Elérte a maximális méretet (5 Mb)</translation>
    </message>
    <message>
        <source>Upload mode:</source>
        <translation>Feltöltés módja :</translation>
    </message>
    <message>
        <source>Remote host closed</source>
        <translation>Távoli állomás lezárva</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>Mégse</translation>
    </message>
    <message>
        <source>Content access denied</source>
        <translation>Tartalom hozzáférés megtagadva</translation>
    </message>
    <message>
        <source>150x150 (thumbnail)</source>
        <translation>150x150 (thumbnail)</translation>
    </message>
    <message>
        <source>Upload now</source>
        <translation>Feltöltés most</translation>
    </message>
    <message>
        <source>Public</source>
        <translation>Nyilvános</translation>
    </message>
    <message>
        <source>Log in to use these features</source>
        <translation>Ezen funkciók használatához jelentkezzen be</translation>
    </message>
    <message>
        <source>Temporary network failure</source>
        <translation>Ideiglenes hálózati hiba</translation>
    </message>
    <message>
        <source>Proxy connection closed</source>
        <translation>Proxy kapcsolat lezárva</translation>
    </message>
    <message>
        <source>anonymous</source>
        <translation>névtelen</translation>
    </message>
    <message>
        <source>Unknown network</source>
        <translation>Ismeretlen hálózat</translation>
    </message>
    <message>
        <source>Connection refused</source>
        <translation>Kapcsolat elutasítva</translation>
    </message>
    <message>
        <source>Protocol failure</source>
        <translation>Protokollhiba</translation>
    </message>
    <message>
        <source>Proxy authentication required</source>
        <translation>Proxyhitelesítés szükséges</translation>
    </message>
    <message>
        <source>Total upload progress:</source>
        <translation>Teljes feltöltési folyamat :</translation>
    </message>
    <message>
        <source>Private</source>
        <translation>Adatvédelem</translation>
    </message>
    <message>
        <source>Upload Error:</source>
        <translation>Feltöltési hiba :</translation>
    </message>
    <message>
        <source>File loaded: %1</source>
        <translation>Fájl betöltve: %1</translation>
    </message>
    <message>
        <source>Log in to use this features</source>
        <translation>Lépjen be ezen szolgáltatások használatához</translation>
    </message>
    <message>
        <source>Protocol invalid operation</source>
        <translation>Érvénytelen protokoll művelet</translation>
    </message>
    <message>
        <source>1024x1024 (15-inch monitor)</source>
        <translation>1024x1024 (15-colos monitor)</translation>
    </message>
    <message>
        <source>&lt;b&gt;Privacy:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Adatvédelem:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Operation canceled</source>
        <translation>Művelet megszakítva</translation>
    </message>
    <message>
        <source>&lt;b&gt;Tags:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Címkék:&lt;/b&gt;</translation>
    </message>
    <message>
        <source>Content not found</source>
        <translation>A tartalom nem található</translation>
    </message>
    <message>
        <source>Authentication required</source>
        <translation>Hitelesítés szükséges</translation>
    </message>
    <message>
        <source>SSL handshake failed</source>
        <translation>Sikertelen SSL handshake művelet</translation>
    </message>
    <message>
        <source>Content operation not permitted</source>
        <translation>A tartalmi művelet nem engedélyezett</translation>
    </message>
    <message>
        <source>Timeout</source>
        <translation>Időtúllépés</translation>
    </message>
    <message>
        <source>640x640 (for message boards)</source>
        <translation>640x640 (üzenőfalakhoz)</translation>
    </message>
    <message>
        <source>1600x1600 (21-inch monitor)</source>
        <translation>1600x1600 (21-colos monitor)</translation>
    </message>
    <message>
        <source>File(s) loaded: %1</source>
        <translation>Fájl (ok) betöltve: %1</translation>
    </message>
    <message>
        <source>Upload in progress...</source>
        <translation>Feltöltés folyamatban...</translation>
    </message>
    <message>
        <source>Unknown content</source>
        <translation>Ismeretlen tartalom</translation>
    </message>
    <message>
        <source>Unknown proxy</source>
        <translation>Ismeretlen proxy</translation>
    </message>
    <message>
        <source>Unknown error</source>
        <translation>Ismeretlen hiba</translation>
    </message>
    <message>
        <source>Do not resize</source>
        <translation>Nincs átméretezés</translation>
    </message>
    <message>
        <source>Proxy timeout</source>
        <translation>Proxy időtúllépés</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Authentication required to set Privacy and Tags on your thumbnail&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Sign in&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-size:8pt;&quot;&gt;Adatvédelem és a címkék hitelesítése szükséges a thumbnailhoz&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;a href=&quot;http://my.imageshack.us/registration&quot;&gt;&lt;span style=&quot; font-size:8pt; text-decoration: underline; color:#0000ff;&quot;&gt;Belépés&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>IniManager</name>
    <message>
        <source>Save Configuration File</source>
        <translation>Konfigurációs fájl mentése</translation>
    </message>
    <message>
        <source>Open Configuration File</source>
        <translation>Konfigurációs fájl megnyitása</translation>
    </message>
    <message>
        <source>Configuration file</source>
        <translation>Konfigurációs fájl</translation>
    </message>
    <message>
        <source>Configuration file loaded</source>
        <translation>Konfigurációs fájl betöltve</translation>
    </message>
    <message>
        <source>Not recent files</source>
        <translation>Nincsenek legutóbbi fájlok</translation>
    </message>
    <message>
        <source> saved successfully</source>
        <translation> sikeresen mentve</translation>
    </message>
    <message>
        <source>Configuration file(*.ini)</source>
        <translation>Konfigurációs fájl(*.ini)</translation>
    </message>
    <message>
        <source>Incorrect settings file</source>
        <translation>Helytelen beállítások fájl</translation>
    </message>
</context>
<context>
    <name>LanguagesSettingsTab</name>
    <message>
        <source>Czech</source>
        <translation>Cseh</translation>
    </message>
    <message>
        <source>Dutch</source>
        <translation>Holland</translation>
    </message>
    <message>
        <source>Italian</source>
        <translation>Olasz</translation>
    </message>
    <message>
        <source>French</source>
        <translation>Francia</translation>
    </message>
    <message>
        <source>German</source>
        <translation>Német</translation>
    </message>
    <message>
        <source>More information at</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>More information at</translation>
    </message>
    <message>
        <source>Help us to translate</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>Help us to translate</translation>
    </message>
    <message>
        <source>Spanish</source>
        <translation>Spanyol</translation>
    </message>
    <message>
        <source>English</source>
        <translation>Angol</translation>
    </message>
    <message>
        <source>Select a language</source>
        <translation>Válasszon egy nyelvet</translation>
    </message>
    <message>
        <source>Can&apos;t see your language in this list?</source>
        <comment>Don&apos;t translate this sentence</comment>
        <translation>Can&apos;t see your language in this list?</translation>
    </message>
    <message>
        <source>Hungarian</source>
        <translation>Magyar</translation>
    </message>
    <message>
        <source>Croatian</source>
        <translation>Horvát</translation>
    </message>
    <message>
        <source>Portuguese</source>
        <translation>Portugál</translation>
    </message>
    <message>
        <source>Chinese</source>
        <translation>Kínai</translation>
    </message>
    <message>
        <source>Russian</source>
        <translation>Orosz</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>Last configuration file cannot be opened. The configuration layout will be reset.</source>
        <translation>Az utolsó konfigurációs fájl nem nyitható meg. A konfigurációs elrendezés vissza lesz állítva.</translation>
    </message>
    <message>
        <source>Would you like save current configuration before exit Thumbnail me?</source>
        <translation>Szeretné menteni az aktuális konfigurációt a Thumbnail me bezárása előtt ?</translation>
    </message>
    <message>
        <source>saved successfully</source>
        <translation>sikeresen mentve</translation>
    </message>
    <message>
        <source>contains no truetype fonts files. Please choose another fonts folder in Settings Menu.</source>
        <translation>nem tartalmaz truetype betű fájlokat. Kérjük, válasszon másik betű mappát a Beállítások menüben.</translation>
    </message>
    <message>
        <source>Toolbar</source>
        <translation>Eszköztár</translation>
    </message>
    <message>
        <source>File</source>
        <translation>Fájl</translation>
    </message>
    <message>
        <source>Edition</source>
        <translation>Kiadás</translation>
    </message>
    <message>
        <source>View</source>
        <translation>Nézet</translation>
    </message>
    <message>
        <source>Predefined Configuration</source>
        <translation>Elő-definiált konfiguráció</translation>
    </message>
    <message>
        <source>About</source>
        <translation>Névjegy</translation>
    </message>
    <message>
        <source>Configuration</source>
        <translation>Konfiguráció</translation>
    </message>
    <message>
        <source>Open</source>
        <translation>Megnyitás</translation>
    </message>
    <message>
        <source>Import a configuration file</source>
        <translation>Konfigurációs fájl importálása</translation>
    </message>
    <message>
        <source>Import a recent configuration file</source>
        <translation>Legutóbbi konfigurációs fájl importálása</translation>
    </message>
    <message>
        <source>Save my current configuration</source>
        <translation>Aktuális konfiguráció mentése</translation>
    </message>
    <message>
        <source>Save my current configuration as</source>
        <translation>Aktuális konfiguráció mentése másként</translation>
    </message>
    <message>
        <source>Print</source>
        <translation>Nyomtatás</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation>Kilépés</translation>
    </message>
    <message>
        <source>Settings</source>
        <translation>Beállítások</translation>
    </message>
    <message>
        <source>Zoom in</source>
        <translation>Nagyítás</translation>
    </message>
    <message>
        <source>Zoom out</source>
        <translation>Kicsinyítés</translation>
    </message>
    <message>
        <source>Clear all</source>
        <translation>Mind törli</translation>
    </message>
    <message>
        <source>Fullscreen</source>
        <translation>Teljes képernyő</translation>
    </message>
    <message>
        <source>Help</source>
        <translation>Súgó</translation>
    </message>
    <message>
        <source>About QT</source>
        <translation>A QT névjegye</translation>
    </message>
    <message>
        <source>Donate</source>
        <translation>Adományozás</translation>
    </message>
    <message>
        <source>Website</source>
        <translation>Weboldal</translation>
    </message>
</context>
<context>
    <name>NetworkSettingsTab</name>
    <message>
        <source>Port</source>
        <translation>Port</translation>
    </message>
    <message>
        <source>Type</source>
        <translation>Típus</translation>
    </message>
    <message>
        <source>Use proxy server</source>
        <translation>Proxykiszolgáló használata</translation>
    </message>
    <message>
        <source>Authentication</source>
        <translation>Hitelesítés</translation>
    </message>
    <message>
        <source>Proxy Settings</source>
        <translation>Proxy beállítások</translation>
    </message>
    <message>
        <source>Hostname</source>
        <translation>Állomásnév</translation>
    </message>
    <message>
        <source>Password</source>
        <translation>Jelszó</translation>
    </message>
    <message>
        <source>Network Connection</source>
        <translation>Hálózati kapcsolat</translation>
    </message>
    <message>
        <source>Username</source>
        <translation>Felhasználónév</translation>
    </message>
    <message>
        <source>Direct connection</source>
        <translation>Közvetlen kapcsolat</translation>
    </message>
</context>
<context>
    <name>PreviewGraphicView</name>
    <message>
        <source>Saving the file failed</source>
        <translation>A fájl mentése sikertelen</translation>
    </message>
    <message>
        <source>Copy to clipboard</source>
        <translation>Másolás a vágólapra</translation>
    </message>
    <message>
        <source>Open to my default picture viewer</source>
        <translation>Megnyitás az alapértelmezett képnézegetővel</translation>
    </message>
    <message>
        <source>Save As</source>
        <translation>Mentés másként</translation>
    </message>
    <message>
        <source>failed to open this file in your default image viewer.</source>
        <translation>nem sikerült megnyitni a fájlt az alapértelmezett képnézegetővel.</translation>
    </message>
    <message>
        <source>Save File</source>
        <translation>Fájl mentése</translation>
    </message>
    <message>
        <source>No Printer Detected</source>
        <translation>Nem észlelve nyomtató</translation>
    </message>
</context>
<context>
    <name>ProcessingStatusBar</name>
    <message>
        <source>Processing file %1 of %2: %3</source>
        <translation>%1 - %2 fájl feldolgozása : %3</translation>
    </message>
    <message>
        <source>Progression:</source>
        <translation>Folyamat :</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Preferences reading</source>
        <translation>Olvasási beállítások</translation>
    </message>
    <message>
        <source>Initialisation</source>
        <translation>Előkészítés</translation>
    </message>
    <message>
        <source>Widgets initialisation</source>
        <translation>Widget-ek előkészítése</translation>
    </message>
    <message>
        <source>Starting...</source>
        <translation>Indítás...</translation>
    </message>
</context>
<context>
    <name>SettingsWidget</name>
    <message>
        <source>Fonts</source>
        <translation>Betűk</translation>
    </message>
    <message>
        <source>Network</source>
        <translation>Hálózat</translation>
    </message>
    <message>
        <source>Languages</source>
        <translation>Nyelvek</translation>
    </message>
    <message>
        <source>OpenGL version 3.0 or higher is not present on your system. It will be disabled.</source>
        <translation>OpenGL 3.0-as verzió vagy újabb nem található a rendszerben. Ez tiltva lesz.</translation>
    </message>
    <message>
        <source>Settings</source>
        <translation>Beállítások</translation>
    </message>
    <message>
        <source>General</source>
        <translation>Általános</translation>
    </message>
    <message>
        <source>openGL not detected on your system. It will be disabled.</source>
        <translation>Az OpenGL nem észlelhető a rendszerben. Ez tiltva lesz.</translation>
    </message>
</context>
<context>
    <name>SuccessDialog</name>
    <message>
        <source>Close</source>
        <translation>Bezárás</translation>
    </message>
    <message>
        <source>Upload these files to ImageShack</source>
        <translation>Töltsd fel a fájlokat ImageShack-ra</translation>
    </message>
    <message>
        <source>Upload to ImageShack</source>
        <translation>Feltöltés az ImageShack-ra</translation>
    </message>
    <message>
        <source>Open Folder</source>
        <translation>Mappa megnyitása</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Save file as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Fájl mentése másként:&lt;/h1&gt;</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Save file(s) as:&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Fájlok mentése mint:&lt;/h1&gt;</translation>
    </message>
</context>
<context>
    <name>ThumbnailEngine</name>
    <message>
        <source>Select an output folder, please</source>
        <translation>Kérjük, válasszon egy célmappát</translation>
    </message>
    <message>
        <source>No file selected</source>
        <translation>Nincs kijelölt fájl</translation>
    </message>
    <message>
        <source>No file(s) loaded</source>
        <translation>Nincsenek betöltve fájlok</translation>
    </message>
    <message>
        <source>No fonts defined</source>
        <translation>Nincs betűtípus megadva</translation>
    </message>
    <message>
        <source>Mtn binary not found. Operation cancelled.</source>
        <translation>Az MTN bináris nem található. Művelet megszakítva.</translation>
    </message>
    <message>
        <source>Output path does not exist</source>
        <translation>A kimeneti hely nem létezik</translation>
    </message>
</context>
<context>
    <name>ThumbnailListWidget</name>
    <message>
        <source>You must select a file to remove it from the list</source>
        <translation>Válasszon ki egy fájlt a listáról való eltávolításhoz</translation>
    </message>
</context>
<context>
    <name>VerboseWindow</name>
    <message>
        <source>Logs</source>
        <translation>Naplók</translation>
    </message>
    <message>
        <source>Clear all</source>
        <translation>Mind törli</translation>
    </message>
    <message>
        <source>Copy to clipboard</source>
        <translation>Másolás a vágólapra</translation>
    </message>
</context>
</TS>
